force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>Products</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <label>Opportunities</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Product_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>Quotes__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteHandlerclass.cls
public class QuoteHandlerclass {/*
    public static void UpdateQuoteLineItem(List<Quotes__c> qList){
        Set<Id> Ids = new set<Id>();
        for(Quotes__c qa:qList){
            Ids.add(qa.Opportunity_Name__c);
        }
        List<OpportunityLineItem__c> plist = [SELECT Id, Name, Quote_Name__c,Opportunities__c FROM OpportunityLineItem__c WHERE Opportunities__c=:Ids];
        
        List<OpportunityLineItem__c> updatedOpportunityLineItems = new List<OpportunityLineItem__c>();
        
        for (Quotes__c qa : qList) {
            
            for(OpportunityLineItem__c os:plist){
                if(os.Opportunities__c == qa.Opportunity_Name__c){
                   os.Quote_Name__c = qa.Id;
                }
                updatedOpportunityLineItems.add(os);
        }
            
        }
        if (!updatedOpportunityLineItems.isEmpty()) {
            update updatedOpportunityLineItems;
        }
        }*/
    }