force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunities__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI---{0000000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Productes__c.field-meta.xml
<CustomField>
    <fullName>Productes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Productes</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Unit_Rate__c</fullName>
    <label>Unit Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product / Machine Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Products__c/fields/Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price__c</fullName>
    <formula>Quoted_Price__c * Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Power_in_HP__c.field-meta.xml
<CustomField>
    <fullName>Power_in_HP__c</fullName>
    <label>Power in HP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Quantity_In_no_s__c.field-meta.xml
<CustomField>
    <fullName>Quantity_In_no_s__c</fullName>
    <label>Quantity (In no&apos;s)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quoted_Price__c - Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductsRetrivingfororderClass.cls
public class ProductsRetrivingfororderClass {
      @AuraEnabled()
    public static List<Products__c> retrieveProducts(){
        return [ SELECT Name,Product_Name__c, Opportunities__c, Power_in_HP__c, Quantity_In_no_s__c, 
                Discount__c, Discounted_Price__c, Unit_Price__c, Total_Price__c
                FROM Products__c ];
    }
    
    public class ProductUpdateWrapper {
        @AuraEnabled public String Id;
        @AuraEnabled public String Orderid;
    }
    
    @AuraEnabled
    public static void UpdateOrderProducts(List<String> selectedProductIds, Id OrderId) {
        try {
            List<Order_Line_Item__c> OrderLineItemsToInsert = new List<Order_Line_Item__c>();
            
            for (Products__c product : [SELECT Name,Product_Name__c, Opportunities__c,Quantity_In_no_s__c, 
                                        Discount__c, Discounted_Price__c, Unit_Price__c, Total_Price__c
                                        FROM Products__c WHERE Id IN :selectedProductIds])
            {
                                            Order_Line_Item__c lineItem = new Order_Line_Item__c(
                                                Orders__c = OrderId,
                                                Productes__c = product.Id,
                                                Product_Description__c = product.Product_Name__c,
                                                Discount__c = product.Discount__c, 
                                                Unit_Rate__c = product.Unit_Price__c,
                                                Quantity__c = product.Quantity_In_no_s__c);
                                                OrderLineItemsToInsert.add(lineItem);
                                        }
            
              if (!OrderLineItemsToInsert.isEmpty()) {
                insert OrderLineItemsToInsert;
                system.debug('lineitems'+OrderLineItemsToInsert);
            }
        } catch (Exception e) {
            // Handle the exception appropriately
            System.debug('Exception: ' + e.getMessage());
        }
    }
    
}