force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunities__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O - {00000}</displayFormat>
        <label>Order No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Quotes__c.field-meta.xml
<CustomField>
    <fullName>Quotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotes</label>
    <referenceTo>Quotes__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Unit_Rate__c</fullName>
    <label>Unit Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI---{0000000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Machine_Name__c.field-meta.xml
<CustomField>
    <fullName>Machine_Name__c</fullName>
    <label>Machine Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Productes__c.field-meta.xml
<CustomField>
    <fullName>Productes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Productes</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Unit_Rate__c</fullName>
    <label>Unit Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/FinalF__c.field-meta.xml
<CustomField>
    <fullName>FinalF__c</fullName>
    <formula>IF(
    NOT(Discounted_Unit_Price__c==0),
      Discounted_Unit_Price__c * Quantity__c,
    Calculated_Unit_Price__c * Quantity__c
   
    
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunities</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/QuotedQ__c.field-meta.xml
<CustomField>
    <fullName>QuotedQ__c</fullName>
    <formula>Unit_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quoted Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quotes__c.field-meta.xml
<CustomField>
    <fullName>Quotes__c</fullName>
    <label>Quotes</label>
    <referenceTo>Quotes__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderRetrievingHandler.cls
public class OrderRetrievingHandler {
    public static void queryQuoteLineItemsToOrder(List<Order__c> orderList) {
        Set<Id> quoteIds = new Set<Id>();
        for (Order__c order : orderList){
            quoteIds.add(order.Quotes__c);
        }
        List<Quote_Line_Item__c> quoteLineItems = [SELECT Id, Discount__c, FinalF__c, Name, Opportunities__c,Product_Name__c,
                                                   Product__c, ProductName__c, Quantity__c, Quotes__c, Unit_Price__c,QuotedQ__c
                                                   FROM Quote_Line_Item__c
                                                   WHERE Quotes__c IN :quoteIds];
        System.debug('Retrieving data: ' + quoteLineItems);
        
        List<Order_Line_Item__c> orderLineItemsToInsert = new List<Order_Line_Item__c>();
        
        for (Order__c order : orderList) {
            
            for (Quote_Line_Item__c quoteLineItem : quoteLineItems) {
                
                if (quoteLineItem.Quotes__c == order.Quotes__c) {
                    
                    Order_Line_Item__c orderLineItem = new Order_Line_Item__c(
                        Orders__c = order.Id,
                        Machine_Name__c = quoteLineItem.ProductName__c,
                        Product_Description__c = quoteLineItem.Product_Name__c,
                        Quantity__c = quoteLineItem.Quantity__c,
                        Unit_Rate__c = quoteLineItem.Unit_Price__c,
                        Discount__c = quoteLineItem.Discount__c,
                        Productes__c = quoteLineItem.Product__c,
                        Value__c = quoteLineItem.QuotedQ__c
                    );
                    orderLineItemsToInsert.add(orderLineItem);
                    System.debug('Order Line Item added: ' + orderLineItem);
                }
            }
        }
        if (!orderLineItemsToInsert.isEmpty()) {
            insert orderLineItemsToInsert;
            System.debug('Order Line Items inserted successfully');
        }
    }
}