force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunities__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Existing Customer-upgrade</fullName>
            </value>
            <value>
                <fullName>Existing Customer-Replacement</fullName>
            </value>
            <value>
                <fullName>Existing Customer-downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product / Machine Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Products__c/fields/Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price__c</fullName>
    <formula>Quoted_Price__c * Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Power_in_HP__c.field-meta.xml
<CustomField>
    <fullName>Power_in_HP__c</fullName>
    <label>Power in HP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Quantity_In_no_s__c.field-meta.xml
<CustomField>
    <fullName>Quantity_In_no_s__c</fullName>
    <label>Quantity (In no&apos;s)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Quoted_Price__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Price__c</fullName>
    <formula>Unit_Price__c  *  Quantity_In_no_s__c</formula>
    <label>Quoted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quoted_Price__c - Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunities</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/PowerHP__c.field-meta.xml
<CustomField>
    <fullName>PowerHP__c</fullName>
    <label>Power in HP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quotes__c.field-meta.xml
<CustomField>
    <fullName>Quotes__c</fullName>
    <label>Quotes</label>
    <referenceTo>Quotes__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductsRetrivingForQuoteClass.cls
public class ProductsRetrivingForQuoteClass {
    
    @AuraEnabled()
    public static List<Products__c> retrieveProducts(){
        return [ SELECT Name,Product_Name__c, Opportunities__c, Category__c, Sub_Category__c, Quoted_Price__c, Power_in_HP__c, Quantity_In_no_s__c, 
                Discount__c, Discounted_Price__c, Unit_Price__c, Total_Price__c
                FROM Products__c ];
    }
    
    public class ProductUpdateWrapper {
        @AuraEnabled public String Id;
        @AuraEnabled public String Quoteid;
    }
    
    @AuraEnabled
    public static void UpdateQuoteProducts(List<String> selectedProductIds, Id QuoteId) {
        for(string abc : selectedProductIds){
            system.debug('method is'  +abc);
        }
        try {
            List<Quote_Line_Item__c> QuoteLineItemsToInsert = new List<Quote_Line_Item__c>();
            if(selectedProductIds!= null){
                
            
            for (Products__c product : [SELECT Name,Product_Name__c, Opportunities__c, Quoted_Price__c, Power_in_HP__c, Quantity_In_no_s__c, 
                                        Discount__c, Category__c, Sub_Category__c, Discounted_Price__c, Type__c, Unit_Price__c, Total_Price__c
                                        FROM Products__c WHERE Id IN :selectedProductIds]) {
                                            Quote_Line_Item__c lineItem = new Quote_Line_Item__c(
                                                Quotes__c = QuoteId,
                                                Product__c = product.Id,
                                                Product_Name__c = product.Product_Name__c,
                                                Discount__c = product.Discount__c,
                                                Type__c = product.Type__c,
                                                Category1__c = product.Category__c,
                                                SubCategory__c = product.Sub_Category__c,
                                                Unit_Price__c = product.Unit_Price__c,
                                                Quantity__c = product.Quantity_In_no_s__c,
                                                PowerHP__c = product.Power_in_HP__c);
                                            QuoteLineItemsToInsert.add(lineItem);
                                        }
            }
            
            if (!QuoteLineItemsToInsert.isEmpty()) {
                system.debug('lineitems'+QuoteLineItemsToInsert);
                insert QuoteLineItemsToInsert;
                system.debug('lineitems'+QuoteLineItemsToInsert);
            }
        } catch (Exception e) {
            // Handle the exception appropriately
            System.debug('Exception: ' + e.getMessage());
        }
    }
    
}