force-app/main/default/objects/Day_Planner__c/Day_Planner__c.object-meta.xml
<CustomObject>
    <label>Day Planner</label>
    <nameField>
        <label>Day Visit Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Planner__c/fields/Final_Location_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Final_Location_Date_and_Time__c</fullName>
    <label>Final Location Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Day_Planner__c/fields/Initial_Location_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Initial_Location_Date_and_Time__c</fullName>
    <label>Initial Location Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Initialdateandtime.cls
public class Initialdateandtime {
    public static void Updatedatestarttime(){
        Day_Planner__c x = new Day_Planner__c();   
        x.Initial_Location_Date_and_Time__c = Datetime.now();      
        //update x;
    }
    
    public static void Updatedateendtime(){
        Day_Planner__c d = new Day_Planner__c();   
        d.Final_Location_Date_and_Time__c = Datetime.now();      
       // update d;
    }
}