force-app/main/default/objects/Day_Planner__c/Day_Planner__c.object-meta.xml
<CustomObject>
    <label>Day Planner</label>
    <nameField>
        <label>Day Visit Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Day Planners</relationshipLabel>
    <relationshipName>Day_Planners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_Planner__c/fields/Monthly_Planner__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Planner__c</fullName>
    <label>Monthly Planner</label>
    <referenceTo>Monthly_Planner__c</referenceTo>
    <relationshipLabel>Day Planners</relationshipLabel>
    <relationshipName>Day_Planners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Day_Planner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Day_Planner__c.field-meta.xml
<CustomField>
    <fullName>Day_Planner__c</fullName>
    <label>Day Planner</label>
    <referenceTo>Day_Planner__c</referenceTo>
    <relationshipName>Day_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Planner__c/Monthly_Planner__c.object-meta.xml
<CustomObject>
    <label>Monthly Planner</label>
    <nameField>
        <label>Monthly Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Planners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Monthly Planners</relationshipLabel>
    <relationshipName>Monthly_Planners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GeolocationCaptureControllerTest.cls
@isTest
public class GeolocationCaptureControllerTest {
    
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"routes": [{"legs": [{"distance": {"text": "2 km"}}]}]}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    private class MockHttpResponseGenerator2 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"routes": [{"legs": [{"distance": {"text": "2 m"}}]}]}');
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void testUpdateGeolocation() {
        
        // ... Your setup code ...
        Account mill = new Account();
        mill.Name = 'testmill';
        mill.Geo_Location__latitude__s = 12.3456;
        mill.Geo_Location__longitude__s = 78.9012;
        insert mill;
        
        
        //create new Territory
        Territory__c trty = new Territory__c();
        trty.name = 'testTerritory';
        insert trty;
        
        // Create Monthly Planner 
        Monthly_Planner__c mp = new Monthly_Planner__c();
        mp.Name = 'testMonth';
        insert mp;
        
        //Create Day Planner
        Day_Planner__c dp = new Day_Planner__c();
        dp.Monthly_Planner__c = mp.Id; 
        dp.Name = 'testDayPlanner';
        dp.Representative_End_Location__Latitude__s = 12.3456;
        dp.Representative_End_Location__Longitude__s = 78.9012;
        dp.Representative_Initial_Location__latitude__s = 12.3456;
        dp.Representative_Initial_Location__longitude__s = 78.9012;
        
        insert dp;
        
        
        
        // Create a Mill Planner record for testing
        Mill_Planner__c millPlanner = new Mill_Planner__c();
        millPlanner.Day_Planner__c = dp.Id; 
        millPlanner.Area__c = trty.Id; 
        millPlanner.Mill_Name__c = mill.id;
        millPlanner.Start_Location__latitude__s = 12.3456;
        millPlanner.Start_Location__longitude__s = 78.9012;
        insert millPlanner;
        
        
        Test.startTest();
        // Testing Apex classes in MillPlanner__C
        GeolocationCaptureController.updateGeolocation(millPlanner.Id, 12.3456, 78.9012, DateTime.now());
        GeolocationCaptureController2.updateGeolocation(millPlanner.Id, 12.3456, 78.9012, DateTime.now(), DateTime.now());
        GeolocationController_endvisit.updateGeolocation(millPlanner.id, 12.3456, 78.9012, DateTime.now());
     
        
        //testing geo on DayPlanner__C
        StoreLocatorPoint.fetchDayVist(dp.Id);
        StoreLocatorPoint.getNearestAccount(dp.Id, '12.3456', '78.9012', '5');
        StoreLocatorPoint.getNearestAccountBasedOnPinCode(dp.Id, '501510');
        
        //Testing Apex Classes in DayPlanner__c
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        dayStartLocationCapture.updateGeolocation(dp.id, 12.3456, 78.9012);
        dayEndLocationCapture.updateGeolocation(dp.id, 12.3456, 78.9012);
        
        Test.stopTest();
        
        // Retrieve the updated Mill Planner record
        Mill_Planner__c updatedMillPlanner = [SELECT Start_Location__Latitude__s, Start_Location__Longitude__s, Status__c
                                              FROM Mill_Planner__c WHERE Id = :millPlanner.Id];
        
        // Perform assertions to verify the update
        System.assertEquals(12.3456, updatedMillPlanner.Start_Location__Latitude__s);
        System.assertEquals(78.9012, updatedMillPlanner.Start_Location__Longitude__s);
        
    }
    
    @isTest
    static void testDistanceGeolocation() {
        // ... Your setup code ...
         Account mill = new Account();
        mill.Name = 'testmill';
        mill.Geo_Location__latitude__s = 12.3456;
        mill.Geo_Location__longitude__s = 78.9012;
        insert mill;
        
        
        //create new Territory
        Territory__c trty = new Territory__c();
        trty.name = 'testTerritory';
        insert trty;
        
        // Create Monthly Planner 
        Monthly_Planner__c mp = new Monthly_Planner__c();
        mp.Name = 'testMonth';
        insert mp;
        
        //Create Day Planner
        Day_Planner__c dp = new Day_Planner__c();
        dp.Monthly_Planner__c = mp.Id; 
        dp.Name = 'testDayPlanner';
        dp.Representative_End_Location__Latitude__s = 12.3456;
        dp.Representative_End_Location__Longitude__s = 78.9012;
        dp.Representative_Initial_Location__latitude__s = 12.3456;
        dp.Representative_Initial_Location__longitude__s = 78.9012;
        
        insert dp;
        
        
        
        // Create a Mill Planner record for testing
        Mill_Planner__c millPlanner = new Mill_Planner__c();
        millPlanner.Day_Planner__c = dp.Id; 
        millPlanner.Area__c = trty.Id; 
        millPlanner.Mill_Name__c = mill.id;
        millPlanner.Start_Location__latitude__s = 12.3456;
        millPlanner.Start_Location__longitude__s = 78.9012;
        insert millPlanner;
        
        // Set up the mock HTTP callout
        Test.startTest(); // Start a new transaction
        
        // Set up the mock HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Call the distanceGeolocation method with appropriate parameters
        String result = GeolocationCaptureController.distanceGeolocation(millPlanner.Id, '12.3456', '78.9012');
        String result1 = GeolocationCaptureController2.distanceGeolocation(millPlanner.Id, '12.3456', '78.9012');
        dayStartLocationCapture.getEstmatedDistance(dp.Id, '12.3456', '78.9012');
        dayEndLocationCapture.getActualdistance(dp.Id, 12.3456, 78.9012);
        dayEndLocationCapture.getActualdistance(dp.Id, 12.3456, 78.9012);
        
        // Perform assertions to verify the result
        System.assertNotEquals(null, result); 
        System.assertNotEquals(null, result1);
        
        
        // Add more specific assertions as needed
        
        Test.stopTest(); // End the transaction
    }
    
    @isTest
    static void testDistanceGeolocationInMeter() {
        
        // ... Your setup code ...
          Account mill = new Account();
        mill.Name = 'testmill';
        mill.Geo_Location__latitude__s = 12.3456;
        mill.Geo_Location__longitude__s = 78.9012;
        insert mill;
        
        
        //create new Territory
        Territory__c trty = new Territory__c();
        trty.name = 'testTerritory';
        insert trty;
        
        // Create Monthly Planner 
        Monthly_Planner__c mp = new Monthly_Planner__c();
        mp.Name = 'testMonth';
        insert mp;
        
        //Create Day Planner
        Day_Planner__c dp = new Day_Planner__c();
        dp.Monthly_Planner__c = mp.Id; 
        dp.Name = 'testDayPlanner';
        dp.Representative_End_Location__Latitude__s = 12.3456;
        dp.Representative_End_Location__Longitude__s = 78.9012;
        dp.Representative_Initial_Location__latitude__s = 12.3456;
        dp.Representative_Initial_Location__longitude__s = 78.9012;
        
        insert dp;
        
        
        
        // Create a Mill Planner record for testing
        Mill_Planner__c millPlanner = new Mill_Planner__c();
        millPlanner.Day_Planner__c = dp.Id; 
        millPlanner.Area__c = trty.Id; 
        millPlanner.Mill_Name__c = mill.id;
        millPlanner.Start_Location__latitude__s = 12.3456;
        millPlanner.Start_Location__longitude__s = 78.9012;
        insert millPlanner;
        
        // Set up the mock HTTP callout
        Test.startTest(); // Start a new transaction
        
        // Set up the mock HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        
        // Call the distanceGeolocation method with appropriate parameters
        String result = GeolocationCaptureController.distanceGeolocation(millPlanner.Id, '12.3456', '78.9012');
        String result1 = GeolocationCaptureController2.distanceGeolocation(millPlanner.Id, '12.3456', '78.9012');
        dayStartLocationCapture.getEstmatedDistance(dp.Id, '12.3456', '78.9012');
        dayEndLocationCapture.getActualdistance(dp.Id, 12.3456, 78.9012);
         dayEndLocationCapture.getActualdistance(dp.Id, 12.3456, 78.9012);
        
        // Perform assertions to verify the result
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result1);// Ensure the result is not null
        // Add more specific assertions as needed
        
        Test.stopTest(); // End the transaction
    }
    
}