force-app/main/default/objects/Day_Planner__c/Day_Planner__c.object-meta.xml
<CustomObject>
    <label>Day Planner</label>
    <nameField>
        <label>Day Visit Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Planner__c/fields/Representative_Initial_Location__c.field-meta.xml
<CustomField>
    <fullName>Representative_Initial_Location__c</fullName>
    <inlineHelpText>Sales rep Location on Site</inlineHelpText>
    <label>Representative Initial Location</label>
    <scale>10</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Day_Planner__c.field-meta.xml
<CustomField>
    <fullName>Day_Planner__c</fullName>
    <label>Day Planner</label>
    <referenceTo>Day_Planner__c</referenceTo>
    <relationshipName>Day_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GoogleShowDirectionsCtrl.cls
public class GoogleShowDirectionsCtrl {
    public String currentRecordId;
    public String startLocation {get;set;}
    public String endLocation {get;set;}
    public List<String> storeVisitString{get;set;}
    public String startDayVisitLat {get;set;}
    public String startDayVisitLng {get;set;}
    List<Mill_Planner__c> storeVisitLocationList{set;get;}
    
    public GoogleShowDirectionsCtrl(ApexPages.StandardController controller) {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        storeVisitString = new List<String>();
        storeVisitLocationList  = [SELECT id, Mill_Name__r.Name, Mill_Name__c, Mill_Name__r.Geo_Location__c,
                                                                  Mill_Name__r.Geo_Location__latitude__s, Day_Planner__r.Representative_Initial_Location__c,
                                                               	   Mill_Name__r.Geo_Location__longitude__s,
                                                                  Day_Planner__r.Representative_Initial_Location__latitude__s,
                                                                  Day_Planner__r.Representative_Initial_Location__longitude__s
                                                                  FROM Mill_Planner__c
                                                                  WHERE Day_Planner__c =: currentRecordId AND Mill_Name__r.Geo_Location__latitude__s != NULL
                                                                  AND Mill_Name__r.Geo_Location__longitude__s != NULL];
        
        for(Mill_Planner__c storeVisitPlan : storeVisitLocationList){
           	storeVisitString.add(string.valueOf(storeVisitPlan.Mill_Name__r.Geo_Location__latitude__s+';'+storeVisitPlan.Mill_Name__r.Geo_Location__longitude__s));
            startDayVisitLat = String.valueOf(storeVisitPlan.Day_Planner__r.Representative_Initial_Location__latitude__s);
            startDayVisitLng = String.valueOf(storeVisitPlan.Day_Planner__r.Representative_Initial_Location__longitude__s);
        }
    }
    
    public List<SelectOption> getstartLocations(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('None','--None--'));
        options.add(new SelectOption(startDayVisitLat+','+startDayVisitLng,'Day Visit Start Location'));       
        for(Mill_Planner__c con : storeVisitLocationList)
        {       
            options.add(new SelectOption(string.valueOf(con.Mill_Name__r.Geo_Location__latitude__s+','+con.Mill_Name__r.Geo_Location__longitude__s),con.Mill_Name__r.Name));
        }        
        return options;
    } 
    
    public List<SelectOption> getendLocations(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('None','--None--'));               
        for(Mill_Planner__c con : storeVisitLocationList)
        {
             
            if(startLocation!=string.valueOf(con.Mill_Name__r.Geo_Location__latitude__s+','+con.Mill_Name__r.Geo_Location__longitude__s)){
                options.add(new SelectOption(string.valueOf(con.Mill_Name__r.Geo_Location__latitude__s+','+con.Mill_Name__r.Geo_Location__longitude__s),con.Mill_Name__r.Name));
            }
             
        }
        return options;
    }
}