force-app/main/default/objects/Day_Planner__c/Day_Planner__c.object-meta.xml
<CustomObject>
    <label>Day Planner</label>
    <nameField>
        <label>Day Visit Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Day Planners</relationshipLabel>
    <relationshipName>Day_Planners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_Planner__c/fields/Monthly_Planner__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Planner__c</fullName>
    <label>Monthly Planner</label>
    <referenceTo>Monthly_Planner__c</referenceTo>
    <relationshipLabel>Day Planners</relationshipLabel>
    <relationshipName>Day_Planners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Day_Planner__c.field-meta.xml
<CustomField>
    <fullName>Day_Planner__c</fullName>
    <label>Day Planner</label>
    <referenceTo>Day_Planner__c</referenceTo>
    <relationshipName>Day_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Planner__c/Monthly_Planner__c.object-meta.xml
<CustomObject>
    <label>Monthly Planner</label>
    <nameField>
        <label>Monthly Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Planners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Planner__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Monthly Planners</relationshipLabel>
    <relationshipName>Monthly_Planners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoogleMapDistanceCtrlTest.cls
@istest
public class GoogleMapDistanceCtrlTest {

    @istest
    static void testGoogleMapDistanceCtrl(){
         // ... Your setup code ...
        Account mill = new Account();
        mill.Name = 'testmill';
        mill.Geo_Location__latitude__s = 12.3456;
        mill.Geo_Location__longitude__s = 78.9012;
        insert mill;
       
        //create new Territory
        Territory__c trty = new Territory__c();
        trty.name = 'testTerritory';
        insert trty;
        
        // Create Monthly Planner 
        Monthly_Planner__c mp = new Monthly_Planner__c();
        mp.Name = 'testMonth';
        insert mp;
        
        //Create Day Planner
        Day_Planner__c dp = new Day_Planner__c();
        dp.Monthly_Planner__c = mp.Id; 
        dp.Name = 'testDayPlanner';
        dp.Representative_End_Location__Latitude__s = 12.3456;
        dp.Representative_End_Location__Longitude__s = 78.9012;
        dp.Representative_Initial_Location__latitude__s = 12.3456;
        dp.Representative_Initial_Location__longitude__s = 78.9012;
        
        insert dp;
       
        // Create a Mill Planner record for testing
        Mill_Planner__c millPlanner = new Mill_Planner__c();
        millPlanner.Day_Planner__c = dp.Id; 
        millPlanner.Area__c = trty.Id; 
        millPlanner.Mill_Name__c = mill.id;
        millPlanner.Start_Location__latitude__s = 12.3456;
        millPlanner.Start_Location__longitude__s = 78.9012;
        insert millPlanner;
        
          // Create a PageReference and set parameters for the page
        PageReference pageRef = Page.GoogleMapDistanceCtrlVf; // Replace with the actual name of your Visualforce page
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', dp.Id);

        // Instantiate the controller
        GoogleMapDistanceCtrl controller = new GoogleMapDistanceCtrl(new ApexPages.StandardController(dp));

        // Perform assertions to verify that the controller properties are set correctly
        System.assertEquals(dp.Id, controller.currentRecordId);
    }
}