force-app/main/default/objects/Day_Planner__c/Day_Planner__c.object-meta.xml
<CustomObject>
    <label>Day Planner</label>
    <nameField>
        <label>Day Visit Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Planner__c/fields/Representative_End_Location__c.field-meta.xml
<CustomField>
    <fullName>Representative_End_Location__c</fullName>
    <inlineHelpText>Sales rep end Location</inlineHelpText>
    <label>Representative End Location</label>
    <scale>10</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Day_Planner__c.field-meta.xml
<CustomField>
    <fullName>Day_Planner__c</fullName>
    <label>Day Planner</label>
    <referenceTo>Day_Planner__c</referenceTo>
    <relationshipName>Day_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mill Planner</relationshipLabel>
    <relationshipName>Day_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Sequence</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/GoogleMapDistanceCtrl.cls
public with sharing class GoogleMapDistanceCtrl {
    public List<String> storeVisitString	{get;set;}
    public String currentRecordId			{get;set;}
    public String startDayVisitLat			{set;get;}
    public String startDayVisitLng			{set;get;}
    public String endDayVisitLat			{set;get;}
    public String endDayVisitLng			{set;get;}
    public String estimatedDistance			{set;get;}
    public List<String> storeNames {get;set;}
    
    
    public GoogleMapDistanceCtrl(ApexPages.StandardController controller) {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        System.debug('currentRecordId====>>>>>>'+currentRecordId);
        storeVisitString = new List<String>();
        storeNames = new List<String>();
        List<Mill_Planner__c> storeVisitLocationList  = [SELECT Id,
                                                                  Mill_Name__r.Name,
                                                                  Mill_Name__r.Geo_Location__latitude__s,
                                                                  Day_Planner__r.Representative_End_Location__c,
                                                                  Day_Planner__r.Representative_Initial_Location__latitude__s,
                                                                  Day_Planner__r.Representative_Initial_Location__longitude__s, 
                                                                  Day_Planner__r.Representative_End_Location__latitude__s,
                                                                  Day_Planner__r.Representative_End_Location__longitude__s,
                                                                  Mill_Name__r.Geo_Location__longitude__s FROM Mill_Planner__c
                                                                  WHERE Day_Planner__c =: currentRecordId 
                                                                  AND Mill_Name__r.Geo_Location__latitude__s != NULL
                                                                  AND Mill_Name__r.Geo_Location__longitude__s != NULL 
                                                                  ORDER BY Sequence__c DESC];
         
        for(Mill_Planner__c storeVisit : storeVisitLocationList){
            storeVisitString.add(String.valueOf(storeVisit.Mill_Name__r.Geo_Location__latitude__s+';'+storeVisit.Mill_Name__r.Geo_Location__longitude__s));
            startDayVisitLat = String.valueOf(storeVisit.Day_Planner__r.Representative_Initial_Location__latitude__s);
            startDayVisitLng = String.valueOf(storeVisit.Day_Planner__r.Representative_Initial_Location__longitude__s);
            storeNames.add(storeVisit.Mill_Name__r.Name);
            if(storeVisit.Day_Planner__r.Representative_End_Location__latitude__s != NULL){
                endDayVisitLat = String.valueOf(storeVisit.Day_Planner__r.Representative_End_Location__latitude__s);
                endDayVisitLng = String.valueOf(storeVisit.Day_Planner__r.Representative_End_Location__longitude__s);
            }else{
                endDayVisitLat = String.valueOf(storeVisit.Day_Planner__r.Representative_Initial_Location__latitude__s);
                endDayVisitLng = String.valueOf(storeVisit.Day_Planner__r.Representative_Initial_Location__longitude__s);
            }
        }
    }
}