force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AS-{0000000}</displayFormat>
        <label>Attendance Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Absent_Reason__c.field-meta.xml
<CustomField>
    <fullName>Absent_Reason__c</fullName>
    <inlineHelpText>Absent Reason</inlineHelpText>
    <label>Absent Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Current_Location_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Current_Location_Latitude__c</fullName>
    <label>Current Location Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Current_Location_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Current_Location_Longitude__c</fullName>
    <label>Current Location Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Excused_Absence__c.field-meta.xml
<CustomField>
    <fullName>Excused_Absence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Excused Absence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <label>Representative</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Representative__c/Representative__c.object-meta.xml
<CustomObject>
    <label>Representative</label>
    <nameField>
        <label>Representative</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Representatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GeoLocationController.cls
public with sharing class GeoLocationController {
  /*  @AuraEnabled
    public static void updateGeoLocation(Double checkInLatitude, Double checkInLongitude,
        Double checkOutLatitude, Double checkOutLongitude) {
        
        Attendance__c geoLocation = [SELECT Id, Absent_Reason__c, Name, Date__c,
                                     Excused_Absence__c, Present__c, Present_Coordinates__c, Representative__c
                                     FROM Attendance__c LIMIT 1];
        
        if (geoLocation!= null) {
           
            
            if (checkInLatitude != null && checkInLongitude != null) {
                geoLocation.Current_Location_Latitude__c = checkInLatitude;
                geoLocation.Current_Location_Longitude__c = checkInLongitude;
            }
            
            update geoLocation;
        }
    }
    */
}