force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AS-{0000000}</displayFormat>
        <label>Attendance Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Current_Location_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Current_Location_Latitude__c</fullName>
    <label>Current Location Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Current_Location_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Current_Location_Longitude__c</fullName>
    <label>Current Location Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Logout_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Logout_Latitude__c</fullName>
    <label>Logout Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Logout_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Logout_Longitude__c</fullName>
    <label>Logout Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <label>Representative</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Representative__c/Representative__c.object-meta.xml
<CustomObject>
    <label>Representative</label>
    <nameField>
        <label>Representative</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Representatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendancecaptureTest.cls
@isTest
public with sharing class AttendancecaptureTest {

    static testMethod void validateAttendancecapture() {
    
 Attendance__c att = new Attendance__c(Representative__c='Surekha', Current_Location_Latitude__c=17.4030848, Current_Location_Longitude__c=78.544896,
                                      Logout_Latitude__c=17.4030848,
                                      Logout_Longitude__c=78.544896);
 System.debug(' before inserting new Attendance: ' + att.Representative__c);
    insert att;
 
 Test.startTest();
        List<Attendance__c> attendanceList = new List<Attendance__c>{att};
        Attendancecapture.insertRecord(17.4030848,78.544896);
        Test.stopTest();
 
 // Retrieve the new Attendance
 att = [SELECT Representative__c FROM Attendance__c WHERE Id =:att.Id];
 System.debug('Representative__c : ' + att.Representative__c);
 
 // Test that the Attendance Apex class correctly updated the LoginDateTime
 System.assertEquals('Surekha', att.Representative__c);
}
  
static testMethod void validateAttendancecaptureforUpdate() {
 // To test the update for the Attendance
    //Attendance__c attupdate = new Attendance__c(Representative__c='Surekha2',Current_Location_Latitude__c=17.4030848, Current_Location_Longitude__c=78.544896,
    //                                  Logout_Latitude__c=17.4030848,
     //                                 Logout_Longitude__c=78.544896);
 List<Attendance__c> lstAtt = new List<Attendance__c>();                               
		
	//insert attupdate;
    For(Integer i=1 ;i<=5 ; i++)
			{
				Attendance__c att=new Attendance__c();
				att.representative__c = 'Test Representative '+i;
				lstAtt.add(att);	   
			}
			insert lstAtt;
	
			List<Attendance__c> lstAttendance = [select id,representative__c from Attendance__c ];
			System.assertEquals(5,lstAttendance.size(),'Attendance list size is equal to 5');


    // Define input parameters for the method
   // String attendanceId = attupdate.Id;
	Decimal logoutlat=17.4030848;
    Decimal logoutlong=78.544896;
    
	Test.StartTest();
    System.debug('Inside Test.StartTest() ');
	Attendancecapture.updateLogoutDetails(logoutlat,logoutlong);
    System.debug('After Test.StartTest() ');
    Test.StopTest();
						
 
  // Test that the Attendance Apex class correctly updated the LoginDateTime
    
   lstAttendance=[SELECT Representative__c,LastModifiedDate FROM Attendance__c LIMIT 1];
    
    // Verify the result
        System.assertNotEquals(null, lstAttendance); // The Attendance should be updated and returned
    /*for(Attendance__c a: lstAttendance){
       System.assertEquals(logoutlat, a.Logout_Latitude__c);
    	System.assertEquals(logoutlong, a.Logout_Longitude__c);
    	system.assertNotEquals(null, a.LastModifiedDate, 'This record has been modified');
    } */
}
static testMethod void testfetchAddressFromCoordinates() {
    	Test.startTest();
    
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());  
        String strResp = Attendancecapture.fetchAddressFromCoordinates(17.4030848,78.544896);
    
    	System.assertNotEquals(null, strResp);
    
    	Test.stopTest();
    
    }
}