force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AS-{0000000}</displayFormat>
        <label>Attendance Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/LogOut_Datetime__c.field-meta.xml
<CustomField>
    <fullName>LogOut_Datetime__c</fullName>
    <label>LogOut Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Logout_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Logout_Latitude__c</fullName>
    <label>Logout Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Logout_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Logout_Longitude__c</fullName>
    <label>Logout Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LogoutCapture.cls
public class LogoutCapture {
    /*
         @AuraEnabled public static void updateGeolocation(Id attendanceId, Decimal lat, Decimal lng) {
        Attendance__c attendanceRecord = [SELECT Id,Logout_Longitude__c,Logout_Latitude__c FROM Attendance__c WHERE Id = :attendanceId ];
        attendanceRecord.Logout_Latitude__c = lat;
        attendanceRecord.Logout_Longitude__c = lng;
        system.debug('Thank You for your service');
        system.debug('Have a Nice Day.');
        
             if(lat != null && lng != null){
                 
                 attendanceRecord.LogOut_Datetime__c = datetime.now();
             }
             update attendanceRecord;
         }
*/
}