force-app/main/default/objects/Inbound_Call_Report__c/Inbound_Call_Report__c.object-meta.xml
<CustomObject>
    <label>Inbound Call</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Inbound Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Call</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Call_Report__c/fields/Call_Acknowledged_By__c.field-meta.xml
<CustomField>
    <fullName>Call_Acknowledged_By__c</fullName>
    <label>Call Acknowledged By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Call_Report__c/fields/Call_Classification__c.field-meta.xml
<CustomField>
    <fullName>Call_Classification__c</fullName>
    <label>Call Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inbound_Call_Report__c/fields/Call_Details__c.field-meta.xml
<CustomField>
    <fullName>Call_Details__c</fullName>
    <label>Call Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inbound_Call_Report__c/fields/Call_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Call_Receipt_Date__c</fullName>
    <defaultValue>NOw()</defaultValue>
    <label>Call Receipt Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Inboundcallcontroller.cls
public class Inboundcallcontroller {
   

  /*  public Inboundcallcontroller(ApexPages.StandardController controller) {

  

   


 list< Inbound_Call_Report__c>       icr = [select Name,  Customer_Name__c, Phone_Number__c, Mill_Name__c, Mill_Address__c, 
         Call_Receipt_Date__c, Call_Acknowledged_By__c, Call_Classification__c, Call_Details__c
                 from Inbound_Call_Report__c
         ];

      }
   */  
}