force-app/main/default/objects/Leads__c/Leads__c.object-meta.xml
<CustomObject>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leads__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Account Name(Mill Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Requirement (Order Description)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/EnquiryType__c.field-meta.xml
<CustomField>
    <fullName>EnquiryType__c</fullName>
    <label>Enquiry Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Enquiry</fullName>
            </value>
            <value>
                <fullName>Existing Customer Enquiry</fullName>
            </value>
            <value>
                <fullName>Old Enquiry</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>BUY</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source(Source of Enquiry)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IndiaMart</fullName>
            </value>
            <value>
                <fullName>TradeIndia</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Mestri</fullName>
            </value>
            <value>
                <fullName>Erection Person</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
                <isActive>false</isActive>
                <label>Advertisement</label>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
                <isActive>false</isActive>
                <label>Employee Referral</label>
            </value>
            <value>
                <fullName>External Referral</fullName>
                <isActive>false</isActive>
                <label>External Referral</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
            <value>
                <fullName>Public Relations</fullName>
                <isActive>false</isActive>
                <label>Public Relations</label>
            </value>
            <value>
                <fullName>Seminar Internal</fullName>
                <isActive>false</isActive>
                <label>Seminar Internal</label>
            </value>
            <value>
                <fullName>Seminar Partner</fullName>
                <isActive>false</isActive>
                <label>Seminar Partner</label>
            </value>
            <value>
                <fullName>Trade Show</fullName>
                <isActive>false</isActive>
                <label>Trade Show</label>
            </value>
            <value>
                <fullName>Web</fullName>
                <isActive>false</isActive>
                <label>Web</label>
            </value>
            <value>
                <fullName>Word of mouth</fullName>
                <isActive>false</isActive>
                <label>Word of mouth</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Mobile 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetLeadsFromTradeIndia.cls
/**
* @description       : 
* @author            : Pranav Thatikonda   
* @group             : 
* @last modified on  : 30-10-2023
* @last modified by  : Pranav Thatikonda
**/
global class GetLeadsFromTradeIndia implements Schedulable {  
     private static final String URL = 'https://www.tradeindia.com/utils/my_inquiry.html?userid=1559850&profile_id=1864910&key=7691361075cce7ee188093fa36606b8a';
  @future(callout=true)  
    global static void fetchDataFromURL() {
        // Calculate the start and end date/time dynamically
        DateTime currentDateTime = DateTime.now();
        DateTime startDateTime = currentDateTime.addDays(-1);
        DateTime endDateTime = currentDateTime;
        
        // Format the start and end date/time in the required format
        String startDateTimeStr = startDateTime.format('yyyy-MM-dd');
        String endDateTimeStr = endDateTime.format('yyyy-MM-dd');
        
        // Construct the dynamic URL with the start and end date/time parameters
        String dynamicURL = URL + '&from_date=' + startDateTimeStr + '&to_date=' + endDateTimeStr;
        
        HttpRequest httpRequest = new HttpRequest();
        HttpResponse httpResponse = new HttpResponse();
        Http http = new Http();
        
        httpRequest.setEndpoint(dynamicURL);
        httpRequest.setMethod('GET');
        
        try {
            httpResponse = http.send(httpRequest);
            String responseBody = httpResponse.getBody();
            System.debug('Response: ' + responseBody);
            createLeadsFromData(responseBody);
        } catch (Exception ex) {
            System.debug('Error in HTTP request: ' + ex.getMessage());
        }
    }
    // Method to parse the retrieved data and create Lead records
    global static void createLeadsFromData(String data) {
    if (data != null) {
        List<Object> responseList = (List<Object>) JSON.deserializeUntyped(data);
        
        List<Leads__c> leadsToInsert = new List<Leads__c>();
        
        for (Object obj : responseList) {
            Map<String, Object> leadData = (Map<String, Object>) obj;
            
            Leads__c lead = new Leads__c();
          	
            lead.FirstName__c  = (String) leadData.get('sender_name');
            lead.Phone__c  = (String) leadData.get('sender_mobile');
            lead.Mobile__c = (string) leadData.get('sender_other_mobiles');
            lead.Company__c  = (String) leadData.get('sender_co');
            String queryMessage = (String) leadData.get('message');
            queryMessage = queryMessage.replaceAll('<br\\s*/?>', '\n');
            lead.Description__c = queryMessage;
            lead.Email__c = (String) leadData.get('sender_email');
            lead.Country__c = (string) leadData.get('sender_country');
            lead.State__c= (string) leadData.get('sender_state');
            lead.District__c = (string) leadData.get('sender_city');
            lead.Village__c = (string) leadData.get('address');
            lead.EnquiryType__c = (string) leadData.get('inquiry_type');   
            lead.Lead_Source__c = 'TradeIndia';
       	    leadsToInsert.add(lead);
        }    
        if (!leadsToInsert.isEmpty()) {
            Database.SaveResult[] saveResults = Database.insert(leadsToInsert, false);
            for (Database.SaveResult saveResult : saveResults) {
                if (saveResult.isSuccess()) {
                    System.debug('Lead inserted successfully. ID: ' + saveResult.getId());
                } else {
                    System.debug('Error inserting Lead: ' + saveResult.getErrors()[0].getMessage());
                }
            }
        }
    }
}    
    // Implement the execute method required by the Schedulable interface
    public void execute(SchedulableContext sc) {
        fetchDataFromURL();
    }
}