force-app/main/default/objects/Leads__c/Leads__c.object-meta.xml
<CustomObject>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leads__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Account Name(Mill Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Data_com_key__c.field-meta.xml
<CustomField>
    <fullName>Data_com_key__c</fullName>
    <label>Data.com key</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Requirement (Order Description)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Last_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Transfer_Date__c</fullName>
    <label>Last Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source(Source of Enquiry)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IndiaMart</fullName>
            </value>
            <value>
                <fullName>TradeIndia</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Mestri</fullName>
            </value>
            <value>
                <fullName>Erection Person</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
                <isActive>false</isActive>
                <label>Advertisement</label>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
                <isActive>false</isActive>
                <label>Employee Referral</label>
            </value>
            <value>
                <fullName>External Referral</fullName>
                <isActive>false</isActive>
                <label>External Referral</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
            <value>
                <fullName>Public Relations</fullName>
                <isActive>false</isActive>
                <label>Public Relations</label>
            </value>
            <value>
                <fullName>Seminar Internal</fullName>
                <isActive>false</isActive>
                <label>Seminar Internal</label>
            </value>
            <value>
                <fullName>Seminar Partner</fullName>
                <isActive>false</isActive>
                <label>Seminar Partner</label>
            </value>
            <value>
                <fullName>Trade Show</fullName>
                <isActive>false</isActive>
                <label>Trade Show</label>
            </value>
            <value>
                <fullName>Web</fullName>
                <isActive>false</isActive>
                <label>Web</label>
            </value>
            <value>
                <fullName>Word of mouth</fullName>
                <isActive>false</isActive>
                <label>Word of mouth</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open - Not Contacted</fullName>
                <default>true</default>
                <label>Open - Not Contacted</label>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Not Converted</fullName>
            </value>
            <value>
                <fullName>Closed - Converted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Nurturing</fullName>
                <isActive>false</isActive>
                <label>Nurturing</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <isActive>false</isActive>
                <label>Unqualified</label>
            </value>
            <value>
                <fullName>Working</fullName>
                <isActive>false</isActive>
                <label>Working</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Number_Of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Employees__c</fullName>
    <label>Number Of Employees</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Mobile 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunities__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Customer Event</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Google AdWords</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>IndiaMart</fullName>
            </value>
            <value>
                <fullName>TradeIndia</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Mastri</fullName>
            </value>
            <value>
                <fullName>Erection Person</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
                <isActive>false</isActive>
                <label>Purchased List</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunities__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/convertController.cls
public with sharing class convertController {
    
   /* @AuraEnabled(cacheable=true)
    public static Leads__c getLeadRecords(string LeadId) {
        List<Leads__c> leads =  [SELECT Id, Address__c, Campaign__c, Company__c, CreatedById, CurrencyIsoCode, 
                                 Data_com_key__c, Description__c, Do_Not_Call__c, Email__c, Email_Opt_Out__c, FirstName__c, Industry__c, 
                                 LastName__c, Last_Transfer_Date__c, Name, Lead_Source__c, Owner.Name, OwnerId, Lead_Owner__r.Name, Lead_Status__c, MiddleName__c,
                                 Mobile__c, Number_Of_Employees__c, Partner_Account__c, Phone__c, Rating__c, Salutation__c, Suffix__c, Title__c, Website__c
                                 FROM Leads__c
                                 WHERE Id = :LeadId
                                 LIMIT 1
                                ];
        
        if (!leads.isEmpty()) {
            return leads[0];
        } else {
            return null; // Return null or handle the case when no records are found
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> searchAccounts (String searchTerm){
        List<Account> accLookupList =  new List<Account>();
        if(searchTerm != ''){
            String accountName = '%' + searchTerm + '%';
            accLookupList = [Select Id, Name From Account Where Name like:accountName];
            System.debug('accLookupList'+accLookupList);
            return accLookupList;
        }
        return accLookupList;
    } 
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> searchContacts(String searchTerm) {
        List<Contact> conLookupList =  new List<Contact>();
        if(searchTerm != ''){
            String searchKey = '%' + searchTerm + '%';
            conLookupList = [SELECT Id, Name FROM Contact WHERE Name LIKE :searchKey];
            System.debug('conLookupList'+conLookupList);
            return conLookupList;
        }
        return conLookupList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Opportunities__c> searchOpty(String searchTerm) {
        List<Opportunities__c> oppLookupList =  new List<Opportunities__c>();
        if(searchTerm != ''){
            String searchKey = '%' + searchTerm + '%';
            oppLookupList = [SELECT Id, Name FROM Opportunities__c WHERE Name LIKE :searchKey];
            System.debug('oppLookupList'+oppLookupList);
            return oppLookupList;
        }
        return oppLookupList;
    }    
    
    
    
    
    @AuraEnabled
    public static Account submitAccount(string LeadCompany) {
        Account account = new Account();
        account.Name = LeadCompany;
        insert account;
        update account;
        return account;
    }
    @AuraEnabled
    public static Leads__c updateLead(String leadId) {
        Leads__c lead = [SELECT Id FROM Leads__c WHERE Id = :leadId];
        //lead.Lead_Status__c = 'Closed - Converted';
        update lead;
      //  delete lead;    
        return lead;
    }
    
    @AuraEnabled
    public static Contact submitContact(string Salutation, String FirstName, String LastName,  String AccId) {
        Contact contact = new Contact();
        contact.Salutation = Salutation;
        contact.FirstName = FirstName;
        contact.LastName = LastName;
        contact.AccountId = AccId;
        insert contact;
      //  update contact;
        return contact;
    }
    
    
    
    @AuraEnabled
    public static Opportunities__c submitOpportunity(string LeadCompany,string AccId) {
        Opportunities__c opportunity = new Opportunities__c();
        opportunity.Name = LeadCompany;
        //opportunity.Stage__c = 'Prospecting';
        //opportunity.Close_Date__c = Date.today().addDays(30);
        opportunity.AccountID__c = AccId;
        insert opportunity;
        //update opportunity;
        return opportunity;
        
    }

    @AuraEnabled
    public static void updateAccount(String accountId, String leadCompany) {
        Account acc = new Account(
            Id = accountId,
            Name = leadCompany
        );
        update acc;
    }

    
    @AuraEnabled
    public static void updateExistAccount(String leadCompany){
        System.debug('leadCompany '+leadCompany);
        List<Account> updateAcctList=new List<Account>();
        for(Account a : [select Id,Name from Account where Name=:leadCompany]){
        //update fields of Existing Account Record
            a.Name=leadCompany;
            updateAcctList.add(a);

        }
        update updateAcctList;
    }

    @AuraEnabled
    public static void updateExistContact(String contactname){
        
        System.debug('Name---> '+contactname);
        List<Contact> updateContList=new List<Contact>();
        for(Contact c : [select Id,FirstName,LastName from Contact where Name =:contactname]){
        //update fields of Existing Contact Record
           
        c.ExistingContact__c=contactname;
            
            updateContList.add(c);

        }
        update updateContList;
        
    }   
    @AuraEnabled
    public static void updateExistOppty(String AcctName){
        
        System.debug('AcctName---> '+AcctName);
        List<Opportunities__c> updateOpptyList=new List<Opportunities__c>();
        for(Opportunities__c opp : [select Id,Name from Opportunities__c where Name =:AcctName]){
        //update fields of Existing Contact Record
           
        opp.ExistingOppty__c=AcctName;
            
        updateOpptyList.add(opp);

        }
        update updateOpptyList;
        
    }

*/
    
}