force-app/main/default/objects/Leads__c/Leads__c.object-meta.xml
<CustomObject>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leads__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Building No. &amp; Street</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Account Name(Mill Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/ConvertedAccId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAccId__c</fullName>
    <label>ConvertedAccId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Requirement (Order Description)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source(Source of Enquiry)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IndiaMart</fullName>
            </value>
            <value>
                <fullName>TradeIndia</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Mestri</fullName>
            </value>
            <value>
                <fullName>Erection Person</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
                <isActive>false</isActive>
                <label>Advertisement</label>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
                <isActive>false</isActive>
                <label>Employee Referral</label>
            </value>
            <value>
                <fullName>External Referral</fullName>
                <isActive>false</isActive>
                <label>External Referral</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
            <value>
                <fullName>Public Relations</fullName>
                <isActive>false</isActive>
                <label>Public Relations</label>
            </value>
            <value>
                <fullName>Seminar Internal</fullName>
                <isActive>false</isActive>
                <label>Seminar Internal</label>
            </value>
            <value>
                <fullName>Seminar Partner</fullName>
                <isActive>false</isActive>
                <label>Seminar Partner</label>
            </value>
            <value>
                <fullName>Trade Show</fullName>
                <isActive>false</isActive>
                <label>Trade Show</label>
            </value>
            <value>
                <fullName>Web</fullName>
                <isActive>false</isActive>
                <label>Web</label>
            </value>
            <value>
                <fullName>Word of mouth</fullName>
                <isActive>false</isActive>
                <label>Word of mouth</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open - Not Contacted</fullName>
                <default>true</default>
                <label>Open - Not Contacted</label>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Not Converted</fullName>
            </value>
            <value>
                <fullName>Closed - Converted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Nurturing</fullName>
                <isActive>false</isActive>
                <label>Nurturing</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <isActive>false</isActive>
                <label>Unqualified</label>
            </value>
            <value>
                <fullName>Working</fullName>
                <isActive>false</isActive>
                <label>Working</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Mandal__c.field-meta.xml
<CustomField>
    <fullName>Mandal__c</fullName>
    <label>Mandal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Mobile 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Territorys__c.field-meta.xml
<CustomField>
    <fullName>Territorys__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leads__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunities__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunities__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Customer Event</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Google AdWords</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>IndiaMart</fullName>
            </value>
            <value>
                <fullName>TradeIndia</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Mastri</fullName>
            </value>
            <value>
                <fullName>Erection Person</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
                <isActive>false</isActive>
                <label>Purchased List</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunities__c/fields/Mill_Type__c.field-meta.xml
<CustomField>
    <fullName>Mill_Type__c</fullName>
    <label>Mill Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Old</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadButtonController.cls
/**
* @description       : 
* @author            : Pranav Thatikonda   
* @group             : 
* @last modified on  : 08-09-2023
* @last modified by  : Pranav Thatikonda
**/
public with sharing class LeadButtonController {
    @AuraEnabled(cacheable=true)
    public static Leads__c getLeadRecords(string LeadId) {
        List<Leads__c> leads =  [SELECT Id, Area__c,Village__c, City__c, Mandal__c, ConvertedAccId__c, District__c,State__c, Territorys__c, Country__c, Company__c, Description__c, Email__c, FirstName__c, Industry__c, Pincode__c,
                                 LastName__c, Name, Lead_Source__c, Owner.Name, Lead_Owner__r.Name, Lead_Status__c, MiddleName__c,
                                 Mobile__c  , Phone__c, Rating__c, Salutation__c,  Website__c, Mill_Type__c
                                 FROM Leads__c
                                 WHERE Id = :LeadId
                                 LIMIT 1
                                ];
        
        if (!leads.isEmpty()) {
            return leads[0];
        } else {
            return null; // Return null or handle the case when no records are found
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> searchAccountsPhoneNumber(String searchTerm1) {
        List<Account> accLookupList = new List<Account>();
        if (searchTerm1 != '') {
            String sanitizedTerm = '%' + searchTerm1 + '%';
            
            // Query accounts by name or phone number
            accLookupList = [SELECT Id, Name, Mobile__c FROM Account WHERE (Name LIKE :sanitizedTerm) OR (Mobile__c LIKE :sanitizedTerm) or (Mobiles__c LIKE :sanitizedTerm)];
            
            System.debug('accLookupList: ' + accLookupList);
            return accLookupList;
        }
        return accLookupList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> searchContacts(String searchTerm) {
        List<Contact> conLookupList =  new List<Contact>();
        if(searchTerm != ''){
            String searchKey = '%' + searchTerm + '%';
            conLookupList = [SELECT Id, Name FROM Contact WHERE Name LIKE :searchKey];
            System.debug('conLookupList'+conLookupList);
            return conLookupList;
        }
        return conLookupList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Opportunities__c> searchOpty(String searchTerm) {
        List<Opportunities__c> oppLookupList =  new List<Opportunities__c>();
        if(searchTerm != ''){
            String searchKey = '%' + searchTerm + '%';
            oppLookupList = [SELECT Id, Name FROM Opportunities__c WHERE Name LIKE :searchKey];
            System.debug('oppLookupList'+oppLookupList);
            return oppLookupList;
        }
        return oppLookupList;
    }    
    
    @AuraEnabled
    public static Account submitAccount(string LeadCompany, string LeadMobile1, string LeadMobile2, string LeadEmail, String LeadMillType,string AccountBillingStreet, 
                                        string AccountBillingCity,id AccountBillingTerritory, string AccountBillingDistrict, string AccountBillingMandal, string AccountBillingVillage, string AccountBillingState, string AccountBillingCountry, 
                                        string accountpincode, String LeadSource) {                                         
                                            Account account = new Account();
                                            account.Name = LeadCompany;
                                            account.Mobile__c = LeadMobile1;
                                            account.Mobiles__c = LeadMobile2;
                                            account.Email__c = LeadEmail;
                                            account.Mill_Type__c = LeadMillType;                                          
                                            account.Street__c = AccountBillingStreet;
                                            account.City__c = AccountBillingCity;
                                            account.Village__c = AccountBillingVillage;
                                            account.District__c =   AccountBillingDistrict;
                                            account.State__c = AccountBillingState;
                                            account.Country__c = AccountBillingCountry;
                                            account.Mandal__c = AccountBillingMandal;
                                            account.Area__c = AccountBillingTerritory;
                                            account.Lead_Source__c = LeadSource;
                                            account.Pincode__c = accountpincode;   
                                            insert account;
                                            return account;       
                                        }
    
    
    @AuraEnabled
    public static Contact submitContact(string Salutation, String FirstName, String LastName, string LeadMobile1, string LeadMobile2, string Email, String LeadSource, String LeadMillType,
                                        string ContactMailingStreet, string ContactMailingTerritory, string ContactMailingCity,string ContactMailingMandal,  string ContactMailingState, string ContactMailingVillage, string ContactMailingDistrict, string ContactMailingCountry,
                                        string ContactPincode, String AccId) {
                                            
                                            Contact contact = new Contact();
                                            contact.Salutation = Salutation;
                                            contact.FirstName = FirstName;
                                            contact.LastName = LastName;
                                            contact.MobilePhone = LeadMobile1;
                                            contact.Mobile__c = LeadMobile2;
                                            contact.Email__c= Email;
                                            contact.Mill_Type__c = LeadMillType;
                                            contact.Lead_Source__c = LeadSource;	   
                                            contact.Street__c = ContactMailingStreet;
                                            contact.City__c = ContactMailingCity;
                                            contact.Village__c = ContactMailingVillage;
                                            contact.State__c = ContactMailingState;
                                            contact.Mandal__c = ContactMailingMandal;
                                            contact.District__c = ContactMailingDistrict;
                                            contact.Country__c = ContactMailingCountry;
                                            contact.Territorys__c = ContactMailingTerritory;
                                            contact.Pincode__c = ContactPincode;
                                            contact.AccountId = AccId;
                                            insert contact;
                                            return contact;
                                        }   
   @AuraEnabled
    public static Opportunities__c submitOpportunity(string LeadCompany, String LeadMillType, String LeadSource, string AccId, String FirstName, String LastName ) {
        Opportunities__c opportunity = new Opportunities__c();
        opportunity.Name = LeadCompany;
        opportunity.Close_Date__c = Date.today().addDays(30);
        opportunity.AccountID__c = AccId;
        opportunity.Mill_Type__c = LeadMillType;
        opportunity.Lead_Source__c = LeadSource;
        opportunity.First_Name__c = FirstName;
        opportunity.Last_Name__c = LastName;

        insert opportunity;
        return opportunity;
    }
    
    @AuraEnabled
    public static Account updateAccountName(String accountId, String accountName) {
        
        system.debug('Account IDDDDDD:  ' +accountId);
        system.debug('Account Name:  ' +accountName);
        try {
            Account acc = [SELECT Id, Name FROM Account WHERE Id = :accountId];
            
            if (acc != null) {
                acc.Name = accountName;
                update acc;
                return acc;
            }
        } catch (Exception ex) {
            System.debug('Error updating account name: ' + ex.getMessage());
            throw ex;
        }
        return null;
    }
    
    @AuraEnabled
    public static Contact updateContactAccount(string contactId, string AccountId) {
        system.debug(contactId);
        system.debug(AccountId);
        
        try {
            Contact contact = [SELECT Id, AccountId FROM Contact WHERE Id = :contactId];
            if (contact != null) {
                contact.AccountId = accountId; // Set the AccountId on the Contact record
                update contact; // Update the Contact record
                return contact;
            }
        } catch (Exception ex) {
            System.debug('Error updating contact account: ' + ex.getMessage());
            throw ex;
        }
        return null;
    }
    
    @AuraEnabled
    public static Opportunities__c updateOpportunityAccount(string opportunityId, string AcID) {
        System.debug(opportunityId);
        System.debug(AcID);
        try {
            Opportunities__c opportunity = [SELECT Id, AccountID__c FROM Opportunities__c WHERE Id = :opportunityId];
            if (opportunity != null) {
                opportunity.AccountID__c = AcID; // Set the AccountID__c on the Opportunity record
                update opportunity; // Update the Opportunity record
                return opportunity;
            }
        } catch (Exception ex) {
            System.debug('Error updating opportunity account: ' + ex.getMessage());
            throw ex;
        }
        return null;
    }
    
    @AuraEnabled
    public static Leads__c updateLead(String leadId, Id ConvertedAccId) {
        Leads__c lead = [SELECT Id FROM Leads__c WHERE Id = :leadId];
        lead.ConvertedAccId__c = ConvertedAccId;
        update lead;
        delete lead;
        return lead;
    }
}