force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI---{0000000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice</label>
    <nameField>
        <displayFormat>I - {000000}</displayFormat>
        <label>Proforma Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <formula>Grand_Amount__c  -  Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Grand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Amount__c</fullName>
    <formula>Total_Charges__c  +   GST_Amount__c +  Insurance_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>IF( AND(SGST_Amount__c == 0,CGST_Amount__c == 0) , Total_Charges__c * GST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Amount__c</fullName>
    <formula>Total_Charges__c *  Insurance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Packing_Charges__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges__c</fullName>
    <defaultValue>0.01</defaultValue>
    <label>Packing Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Total_Charges__c.field-meta.xml
<CustomField>
    <fullName>Total_Charges__c</fullName>
    <formula>Sub_Total__c   +   Forwarding_Charges_Amount__c   +   Commissioning_Charges__c    + Packing_Charges_Amount__c</formula>
    <label>Total Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PDFInvoicePageTest.cls
@isTest
public class PDFInvoicePageTest {
    
    @isTest
    static void testPDFInvoicePage() {
        
        Proforma_Invoice__c testInvoice = new Proforma_Invoice__c();
        insert testInvoice;
      
        ApexPages.StandardController standardController = new ApexPages.StandardController(testInvoice);
        
        PDFInvoicePage pdfInvoicePage = new PDFInvoicePage(standardController);
                
        pdfInvoicePage.next();
        System.assertEquals(1, pdfInvoicePage.currentPageIndex, 'Next method should increment currentPageIndex');
        pdfInvoicePage.previous();
        System.assertEquals(0, pdfInvoicePage.currentPageIndex, 'Previous method should decrement currentPageIndex');

        
        Test.startTest();
        PageReference pageRef = pdfInvoicePage.save();
        Test.stopTest();
        
        System.assertNotEquals(null, pageRef);
        
        Attachment testAttachment = [SELECT Id FROM Attachment WHERE ParentId = :testInvoice.Id LIMIT 1];
        System.assertNotEquals(null, testAttachment);
    }    
    @isTest
    static void testPDFInvoicePageSavePdfAsAttachment() {
        Proforma_Invoice__c testInvoice = new Proforma_Invoice__c();
        insert testInvoice;
        
        Blob testPdfBlob = Blob.valueOf('Test PDF Content');
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(testInvoice);
        
        PDFInvoicePage pdfInvoicePage = new PDFInvoicePage(standardController);
        
        Test.startTest();
        pdfInvoicePage.savePdfAsAttachment(testInvoice.Id, 'TestFileName.pdf', testPdfBlob);
        Test.stopTest();
      
    }
    @isTest
    static void testPDFInvoicePageGeneratePdfContent() {
        
        Proforma_Invoice__c testInvoice = new Proforma_Invoice__c();
        insert testInvoice;
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(testInvoice);
        
        PDFInvoicePage pdfInvoicePage = new PDFInvoicePage(standardController);
        
        Test.startTest();
        Blob pdfBlob = pdfInvoicePage.generatePdfContent(testInvoice.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, pdfBlob);
    }
        @isTest
    static void formattedSubTotal() {
        Proforma_Invoice__c testerInvoice = new Proforma_Invoice__c();
        insert testerInvoice;

        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testerInvoice));

        String testFormattedValue = controller.formattedSubTotal;
        System.assertEquals(null, testFormattedValue, 'Unexpected currency formatting');    
    }
        @isTest
    static void formattedPackingCharges() {
        Proforma_Invoice__c TestingInvoice = new Proforma_Invoice__c(Packing_Charges__c = 500000.00);
        insert TestingInvoice;

        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(TestingInvoice));
        
        System.assertNotEquals(null, controller.formattedPackingCharges,'Unexpected currency formatting');
        controller.ORDL = new List<Order_Line_Item__c>();
        System.assertEquals('0', controller.formattedPackingCharges,'Unexpected currency formatting');
    }
        @isTest
    static void testFormattedCommissioningCharges() {
        Proforma_Invoice__c TestingInvoice = new Proforma_Invoice__c(Commissioning_Charges__c = 500000.00);
        insert TestingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(TestingInvoice));
        
        System.assertNotEquals(null, controller.formattedCommissioningCharges,'Unexpected currency formatting');
        controller.ORDL = new List<Order_Line_Item__c>();
        System.assertEquals('5,00,000', controller.formattedCommissioningCharges,'Unexpected currency formatting');
    }
    @isTest
        static void formattedForwardingCharge() {
        Proforma_Invoice__c TestingInvoice = new Proforma_Invoice__c();
        insert TestingInvoice;
            
            PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(TestingInvoice));
        controller.InvoiceList = [SELECT Id,Forwarding_Charges_Amount__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];

        String testFormattedValue = controller.formattedForwardingCharges;
        System.assertEquals('0', testFormattedValue, 'Unexpected currency formatting'); 
    }
        @isTest
    static void formattedTransitInsuranceAmount() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,Insurance_Amount__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedTransitInsuranceAmount = controller.formattedInsuranceAmount;
        System.assertEquals('0', testformattedTransitInsuranceAmount, 'Unexpected currency formatting');
    }
           @isTest
    static void testformattedTotalCharges() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,Total_Charges__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedTotalCharges = controller.formattedTotalCharges;
        System.assertEquals('7,500', testformattedTotalCharges, 'Unexpected currency formatting');
    }       
    @isTest
    static void formattedGSTAmount() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,GST_Amount__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedGSTAmount = controller.formattedGSTAmount;
        System.assertEquals('0', testformattedGSTAmount, 'Unexpected currency formatting');
    }
           @isTest
    static void formattedGrandAmount() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,Grand_Amount__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedGrandAmount = controller.formattedGrandAmount;
        System.assertEquals('7,500', testformattedGrandAmount, 'Unexpected currency formatting');
    }
           @isTest
    static void formattedAmountReceived() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,Amount_Received__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedAmountReceived = controller.formattedAmountReceived;
        System.assertEquals(null, testformattedAmountReceived, 'Unexpected currency formatting');
    }
           @isTest
    static void formattedBalanceAmount() {
        Proforma_Invoice__c testingInvoice = new Proforma_Invoice__c();
        insert testingInvoice;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testingInvoice));
        controller.InvoiceList = [SELECT Id,Balance_Amount__c FROM Proforma_Invoice__c WHERE Id = :testingInvoice.Id LIMIT 1];
        
        String testformattedBalanceAmount = controller.formattedBalanceAmount;
        System.assertEquals('7,500', testformattedBalanceAmount, 'Unexpected currency formatting');
    }
    
        @isTest
    static void testformatIndianCurrency() {
        Decimal testAmount = 10000.50;
        Proforma_Invoice__c testInv = new Proforma_Invoice__c();
        insert testInv;
        
        PDFInvoicePage controller = new PDFInvoicePage(new ApexPages.StandardController(testInv));
        controller.InvoiceList = [SELECT Id FROM Proforma_Invoice__c WHERE Id = :testInv.Id LIMIT 1];
        
        String formattedValue = controller.formatIndianCurrency(testAmount);
        System.assertEquals('10,000.5', formattedValue, 'Unexpected currency formatting');
    }  

}