force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.City__c</formula>
    <label>Billing City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Country__c</formula>
    <label>Billing Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillingStateProvince__c.field-meta.xml
<CustomField>
    <fullName>BillingStateProvince__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.State__c</formula>
    <label>Billing State/Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>BillingStreet__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Street__c</formula>
    <label>Billing Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillingZipPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingZipPostalCode__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Pincode__c</formula>
    <label>Billing Zip/Postal Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/BillToName__c.field-meta.xml
<CustomField>
    <fullName>BillToName__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <formula>IF( OR( BillingStateProvince__c == &apos;Telangana&apos;, BillingStateProvince__c == &apos;telangana&apos;, BillingStateProvince__c == &apos;TELANGANA&apos;), 0.09, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Commissioning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Commissioning Charges For Each Machine</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Contact_Name2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name2__c</fullName>
    <formula>Opportunity_Name__r.Last_Name__c &amp; &quot; &quot; &amp;  Opportunity_Name__r.First_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/FinalFF__c.field-meta.xml
<CustomField>
    <fullName>FinalFF__c</fullName>
    <label>Final Sub Cost</label>
    <summarizedField>Quote_Line_Item__c.FinalF__c</summarizedField>
    <summaryForeignKey>Quote_Line_Item__c.Quotes__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <label>Forwarding Charges (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Forwarding_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges_Amount__c</fullName>
    <formula>QuotedQQ__c *  Forwarding_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forwarding Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/ForwardingCharge__c.field-meta.xml
<CustomField>
    <fullName>ForwardingCharge__c</fullName>
    <label>Forwarding Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>Total_Cost__c +  Transit_Insurance_Charges__c  + IGST_Amount__c +  SGST_Amount__c +  SGST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.GSTIN__c</formula>
    <label>GSTIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <formula>IF(OR( BillingStateProvince__c== &apos;Telangana&apos;, BillingStateProvince__c== &apos;telangana&apos;, BillingStateProvince__c== &apos;TELANGANA&apos;),0,0.18)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/IGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount__c</fullName>
    <formula>Total_Cost__c * VALUE( TEXT( IGST__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Mandal__c.field-meta.xml
<CustomField>
    <fullName>Mandal__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Mandal__c</formula>
    <label>Mandal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunities__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Packing_Charges__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges__c</fullName>
    <label>Packing Charges (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Packing_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges_Amount__c</fullName>
    <formula>QuotedQQ__c   *  Packing_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packing Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/PackingCharge__c.field-meta.xml
<CustomField>
    <fullName>PackingCharge__c</fullName>
    <label>Packing Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Mobile__c</formula>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <displayFormat>QN-{000000}</displayFormat>
    <label>Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/QuotedQQ__c.field-meta.xml
<CustomField>
    <fullName>QuotedQQ__c</fullName>
    <label>Quoted Sub Cost</label>
    <summarizedField>Quote_Line_Item__c.QuotedQ__c</summarizedField>
    <summaryForeignKey>Quote_Line_Item__c.Quotes__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <formula>IF( OR( BillingStateProvince__c  == &apos;Telangana&apos;, BillingStateProvince__c  == &apos;telangana&apos;, BillingStateProvince__c  == &apos;TELANGANA&apos;), 0.09, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <formula>Total_Cost__c * VALUE( TEXT( SGST__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/SGST_Amount_Final__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount_Final__c</fullName>
    <formula>Total_CostF_c__c * VALUE(text( SGST__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount Final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Area__r.Name</formula>
    <label>Territory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Total_PowerPP__c.field-meta.xml
<CustomField>
    <fullName>Total_PowerPP__c</fullName>
    <label>Total Power Required</label>
    <summarizedField>Quote_Line_Item__c.PowerHP__c</summarizedField>
    <summaryForeignKey>Quote_Line_Item__c.Quotes__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Village__c</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcButtonQuotation.cls
public class LwcButtonQuotation {
    
    public Quotes__c  qu{get;set;}
    
    public String currentRecordId{get;set;}
    

    public LwcButtonQuotation(){
        
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        
        if(currentRecordId != null && String.isNotBlank(currentRecordId)){
            
            qu = [SELECT Id,  Account_Name__c,  GSTIN__c,Date__c, BillingStreet__c, BillToName__c, Contact_Name2__c,
                 Commissioning_Charges__c, Phone__c, Contact_Name__c, Village__c, Mandal__c, District__c, Territory__c, BillingZipPostalCode__c,
                 BillingCity__c, BillingStateProvince__c, BillingCountry__c,IGST__c,IGST_Amount__c, CGST__c, SGST__c, SGST_Amount__c, SGST_Amount_Final__c,
                 Description__c, Email__c, Forwarding_Charges__c, Forwarding_Charges_Amount__c, Grand_Total__c, PackingCharge__c, ForwardingCharge__c,
                 Opportunity_Name__c, Packing_Charges__c, Packing_Charges_Amount__c, Name, Quote_Number__c, Ship_To__c, QuotedQQ__c, FinalFF__c,
                 Total_PowerPP__c, Ship_To_Name__c, Status__c, Packing_Charges_AmountF_c__c, Forwarding_Charges_AmountF_c__c, Transit_Insurance_ChargesF_c__c, 
                 Machine_Required__c, Total_CostF_c__c, GST_AmountF_c__c, Total_Commissioning_Charges__c, Grand_TotalF_c__c, Total_Cost__c, 
                 Transit_Insurance__c,Transit_Insurance_Charges__c FROM Quotes__c WHERE Id =:currentRecordId];       
        }
        
        System.debug('Currentid: ' + currentRecordId);
        
    }
    
    
    
    
    
    @AuraEnabled
    
    public static String sendPdf(String recordId) {
        
        PageReference pdf = new pagereference('/apex/QuotationPDF?id='+recordId);
        
        pdf.getParameters().put('id', recordId);
        
        System.debug('Recordid: ' + recordId);
        
        Blob body;
        
        try {
            
            // returns page as a PDF
            
            body = pdf.getContent();
            
        } catch (Exception e) {
            
            body = Blob.valueOf('data');
            
        }
        
        
        
        //insert content version
        
        ContentVersion CV = new ContentVersion();
        
        // Specify the PDF type
        String pdfType = 'Final Quote';
        
        // Query existing ContentVersions for the same recordId and PDF type
        List<ContentVersion> existingVersions = [SELECT Id, Title FROM ContentVersion WHERE FirstPublishLocationId = :recordId AND Title LIKE :pdfType + '-%' ORDER BY CreatedDate DESC LIMIT 1];
        
        String versionLabel;
        Integer lastVersionNumber = 1; // Initialize with 1 by default
        
        if (!existingVersions.isEmpty()) {
            // If there are existing versions, determine the version label (S1, S2, etc.)
            String existingTitle = existingVersions[0].Title;
            
            // Extract the version number from the existing title
            try {
                String lastVersionLabel = existingTitle.substringAfter('V');
                lastVersionNumber = Integer.valueOf(lastVersionLabel);
                lastVersionNumber++;
            } catch (Exception e) {
                // Handle any exceptions if the existing title doesn't follow the expected format
            }
        }
        
        versionLabel = 'V' + lastVersionNumber;
        String uniqueNumber = pdfType + '-' + versionLabel;
        
        CV.Title = uniqueNumber;
        CV.PathOnClient = pdfType + '.pdf';
        CV.VersionData = body;
        CV.FirstPublishLocationId = recordId;
        
        insert CV;
        
        // Update the custom field on the Quote object to store the last version number for this PDF type
        if (!existingVersions.isEmpty()) {
            Quotes__c quote = [SELECT Id, LastVersionNumber__c FROM Quotes__c WHERE Id = :recordId LIMIT 1];
            quote.LastVersionNumber__c = lastVersionNumber;
            update quote;
        }
        
        
        
        
        
                    /* Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            
            attach.setContentType('application/pdf');
            
            attach.setFileName('RiceTec CC Commnication.pdf');
            
            attach.Body = body;
            
            
            
            Cases__c cmail = [SELECT Email__c FROM Cases__c WHERE Id = :recordId];
            
            
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            mail.setToAddresses(new String[] {cmail.Email__c});
            
            mail.setSubject(' PDF from RiceTec Machinery India Pvt. Ltd.,');
            
            mail.setHtmlBody('PDF for the Customer Complaint Communication');
            
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] {attach});
            
            // Send the email
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            
            return 'Email sent Successfully with PDF.';*/
        return 'PDF saved successfully.';
        
    }
    
}