force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/SpareLineItem__c.object-meta.xml
<CustomObject>
    <label>Spare Products</label>
    <nameField>
        <label>Spare Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spare Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SpareLineItem__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>SpareLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Dept__c.field-meta.xml
<CustomField>
    <fullName>Dept__c</fullName>
    <label>Dept</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/RS_EA__c.field-meta.xml
<CustomField>
    <fullName>RS_EA__c</fullName>
    <label>RS/EA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/RS_SET__c.field-meta.xml
<CustomField>
    <fullName>RS_SET__c</fullName>
    <label>RS/SET</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Spare_Description_of_Material__c.field-meta.xml
<CustomField>
    <fullName>Spare_Description_of_Material__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Std_Qty__c.field-meta.xml
<CustomField>
    <fullName>Std_Qty__c</fullName>
    <label>Std Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Final_Price__c*Units__c</formula>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Spare Products</relationshipLabel>
    <relationshipName>Spare_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/Work_Order_for_Spares__c.object-meta.xml
<CustomObject>
    <label>WorkOrder</label>
    <nameField>
        <displayFormat>WorkOrder-{mm}{dd}-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Basic Order Value</label>
    <summarizedField>WorkOrderSparesLine__c.TPrice__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/WorkOrderSparesLine__c.object-meta.xml
<CustomObject>
    <label>Work Orders</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work OrdersLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Diagram__c.field-meta.xml
<CustomField>
    <fullName>Diagram__c</fullName>
    <label>Diagram</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Required_On_or_Before__c.field-meta.xml
<CustomField>
    <fullName>Required_On_or_Before__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/RS_EA__c.field-meta.xml
<CustomField>
    <fullName>RS_EA__c</fullName>
    <label>RS/EA</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/RS_SET__c.field-meta.xml
<CustomField>
    <fullName>RS_SET__c</fullName>
    <label>RS/SET</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Work_Order_for_Spares__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_for_Spares__c</fullName>
    <label>Work Order for Spares</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WO2Workspareline.cls
public with sharing class WO2Workspareline {
    public static void convertSpareline2WOLI(List<Work_Order_for_Spares__c> qList) {
        Set<Id> Ids = new set<Id>();
        for(Work_Order_for_Spares__c qa:qList){
            Ids.add(qa.Case__c);
        }
        List<SpareLineItem__c>  spareLineItems=[ SELECT Cases__c,Dept__c,Diagram__c,Id,
                                                MC_Name__c,Name,Price__c,Product_Code__c,Product_Name__c,
                                                Required_On_or_Before__c,RS_EA__c,RS_SET__c,Size__c,
                                                Spare_Description_of_Material__c,Sr_No__c,Std_Qty__c,Total_Price__c,Units__c,Work_Order__c 
                                                FROM SpareLineItem__c
                                                WHERE Cases__c = :Ids];
        
        
        List<WorkOrderSparesLine__c> SpareLineItemsToInsert = new List<WorkOrderSparesLine__c>();
        for(Work_Order_for_Spares__c q:qList){
            
            for (SpareLineItem__c oli : spareLineItems) {
                
                   WorkOrderSparesLine__c qli = new WorkOrderSparesLine__c(
                         cases__c=q.case__c,
                         Work_Order_for_Spares__c=q.Id,
                         MC_Name__c = oli.MC_Name__c,
                         Diagram__c=oli.Diagram__c,
                         Product_Code__c=oli.Product_Code__c,
                         Product_Name__c=oli.Spare_Description_of_Material__c,
                         Size__c=oli.Size__c,
                         Quantity__c=oli.Units__c,
                         RS_EA__c=oli.RS_EA__c,
                         RS_SET__c=oli.RS_SET__c,
                     
                         Required_On_or_Before__c=oli.Required_On_or_Before__c
                                            
                );
                    SpareLineItemsToInsert.add(qli);
                    system.debug('WorkLine Item added: ' + qli);
                            }
        }
        
        if (!SpareLineItemsToInsert.isEmpty()) {
            insert SpareLineItemsToInsert;
            system.debug('WorkLine Items inserted successfully');
        }
    }
}