force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Accountant_Sign__c.field-meta.xml
<CustomField>
    <fullName>Accountant_Sign__c</fullName>
    <label>Accountant Sign.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/C_C_Acknowledged_by__c.field-meta.xml
<CustomField>
    <fullName>C_C_Acknowledged_by__c</fullName>
    <label>C C Acknowledged by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Complaint Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Receipt_Date__c</fullName>
    <label>Complaint Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerName2__c.field-meta.xml
<CustomField>
    <fullName>CustomerName2__c</fullName>
    <label>Customer Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerNameNew__c.field-meta.xml
<CustomField>
    <fullName>CustomerNameNew__c</fullName>
    <formula>Contact_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date_of_Commissioning__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Commissioning__c</fullName>
    <label>Date of Commissioning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date_of_Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Dispatch__c</fullName>
    <label>Date of Dispatch</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Datec__c.field-meta.xml
<CustomField>
    <fullName>Datec__c</fullName>
    <inlineHelpText>Corrective Action</inlineHelpText>
    <label>(CA)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Datep__c.field-meta.xml
<CustomField>
    <fullName>Datep__c</fullName>
    <inlineHelpText>Preventive Action</inlineHelpText>
    <label>(PA)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Debit_Note_No__c.field-meta.xml
<CustomField>
    <fullName>Debit_Note_No__c</fullName>
    <label>Debit Note No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Designinig_cost__c.field-meta.xml
<CustomField>
    <fullName>Designinig_cost__c</fullName>
    <label>Designinig cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Designing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Designing_Cost__c</fullName>
    <label>Details of Designing Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Others__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Others__c</fullName>
    <label>Details of Others</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_QC_cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_QC_cost__c</fullName>
    <label>Details of QC cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Rework_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Rework_Cost__c</fullName>
    <label>Details of Rework Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Spares_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Spares_Cost__c</fullName>
    <label>Details of Spares Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Transport_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Transport_Cost__c</fullName>
    <label>Details of Transport Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Enclosures__c.field-meta.xml
<CustomField>
    <fullName>Enclosures__c</fullName>
    <label>Enclosures</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Initial_DC_No__c.field-meta.xml
<CustomField>
    <fullName>Initial_DC_No__c</fullName>
    <label>Initial DC No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/IS_CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>IS_CAPA_Required__c</fullName>
    <label>IS CAPA Required ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine No.</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Cases (Machine No.)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/ModeofReceipt__c.field-meta.xml
<CustomField>
    <fullName>ModeofReceipt__c</fullName>
    <label>Mode of Receipt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Name_of2_Participant__c.field-meta.xml
<CustomField>
    <fullName>Name_of2_Participant__c</fullName>
    <label>Name of Participant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Name_of3_Participant__c.field-meta.xml
<CustomField>
    <fullName>Name_of3_Participant__c</fullName>
    <label>Name of Participant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Name_of4_Participant__c.field-meta.xml
<CustomField>
    <fullName>Name_of4_Participant__c</fullName>
    <label>Name of Participant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Name_of_Participant__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Participant__c</fullName>
    <label>Name of Participant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Obsesrvations_status_QC__c.field-meta.xml
<CustomField>
    <fullName>Obsesrvations_status_QC__c</fullName>
    <label>Obsesrvations status(QC)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Order_No_del__c.field-meta.xml
<CustomField>
    <fullName>Order_No_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Ordernew__c.field-meta.xml
<CustomField>
    <fullName>Ordernew__c</fullName>
    <label>Order No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Others__c.field-meta.xml
<CustomField>
    <fullName>Others__c</fullName>
    <label>Others</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber2__c</fullName>
    <label>Phone Number 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Prepared_By__c.field-meta.xml
<CustomField>
    <fullName>Prepared_By__c</fullName>
    <defaultValue>&quot;Incharge - Service&quot;</defaultValue>
    <label>Prepared By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Preventive_Action__c.field-meta.xml
<CustomField>
    <fullName>Preventive_Action__c</fullName>
    <label>Preventive Action</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/QC_cost__c.field-meta.xml
<CustomField>
    <fullName>QC_cost__c</fullName>
    <label>QC cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/QC_Sign__c.field-meta.xml
<CustomField>
    <fullName>QC_Sign__c</fullName>
    <label>QC Sign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Re_Occurance__c.field-meta.xml
<CustomField>
    <fullName>Re_Occurance__c</fullName>
    <label>Re-Occurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Returnable_DC_No__c.field-meta.xml
<CustomField>
    <fullName>Returnable_DC_No__c</fullName>
    <label>Returnable DC No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_CBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_CBy__c</fullName>
    <label>(Corrective Action)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_PBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_PBy__c</fullName>
    <label>(Preventive Action)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_RBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_RBy__c</fullName>
    <label>(Root Cause)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Rework_Cost__c.field-meta.xml
<CustomField>
    <fullName>Rework_Cost__c</fullName>
    <label>Rework Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <label>Root Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Signature1__c.field-meta.xml
<CustomField>
    <fullName>Signature1__c</fullName>
    <formula>IMAGE(&quot;/resource/testsign&quot;, &quot;Sign&quot;, 30, 70)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Signature2__c.field-meta.xml
<CustomField>
    <fullName>Signature2__c</fullName>
    <formula>IMAGE(&quot;/resource/testsign&quot;, &quot;Sign&quot;, 30, 70)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Signature3__c.field-meta.xml
<CustomField>
    <fullName>Signature3__c</fullName>
    <formula>IMAGE(&quot;/resource/testsign&quot;, &quot;Sign&quot;, 30, 70)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Sl_No__c.field-meta.xml
<CustomField>
    <fullName>Sl_No__c</fullName>
    <label>Sl. No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Spares_cost__c.field-meta.xml
<CustomField>
    <fullName>Spares_cost__c</fullName>
    <label>Spares cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Stores_GRN_No__c.field-meta.xml
<CustomField>
    <fullName>Stores_GRN_No__c</fullName>
    <label>Stores GRN No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Stores_Signature__c.field-meta.xml
<CustomField>
    <fullName>Stores_Signature__c</fullName>
    <label>Stores Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Transport_Cost__c.field-meta.xml
<CustomField>
    <fullName>Transport_Cost__c</fullName>
    <label>Transport Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O - {00000}</displayFormat>
        <label>Order No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Casescomplaintcontroller.cls
public class Casescomplaintcontroller {
    public Id id { get; set; }
    public List<Cases__c> cont { get; set; }
    // public Cases__c c { get; set; }
    public ApexPages.StandardSetController controller { get; set; }
    
    public Casescomplaintcontroller(ApexPages.StandardController stdController) {
        Id caseId = stdController.getId();
        cont = [SELECT Id,Name,Stores_GRN_No__c,Machine_No__r.Name,Customer_Name__c, CustomerNameNew__c,Returnable_DC_No__c, Order_No_del__r.Name,
                Initial_DC_No__c,Sl_No__c,ModeofReceipt__c, CustomerName2__c,  PhoneNumber2__c, Complaint_Receipt_Date__c,Date_of_Dispatch__c,Date_of_Commissioning__c,
                Machine_No__c, Complaint_Date__c, Enclosures__c, Complaint_Details__c, Reviewed_CBy__c, Reviewed_RBy__c, Ordernew__c,
                Details_of_Designing_Cost__c, Details_of_Others__c, Details_of_QC_cost__c, Details_of_Rework_Cost__c, Details_of_Spares_Cost__c, Details_of_Transport_Cost__c,
                Reviewed_PBy__c,Preventive_Action__c,Root_Cause__c,Date__c,Stores_Signature__c,Datep__c,Datec__c, IS_CAPA_Required__c,
                Re_Occurance__c,C_C_Acknowledged_by__c,Accountant_Sign__c,Debit_Note_No__c, Debit_Note_Date__c,Name_of_Participant__c,Name_of4_Participant__c,
                Name_of2_Participant__c,Name_of3_Participant__c,QC_Sign__c,Designinig_cost__c,Rework_Cost__c,Spares_cost__c,Obsesrvations_status_QC__c, 
                QC_cost__c, Transport_Cost__c,Prepared_By__c,Signature2__c,Signature1__c,Signature3__c,Reviewed_By__c,Verified_Results__c,SignatureI__c,
                SignatureD__c,SignatureM__c,DateIS__c,DateDp__c,DateAB__c,Corrective_Action__c,Complaint_Classification__c,Machine_Name__c,
                Received_by_Sign__c,Checked_by_Sign_ASM__c,Verified_by_Sign_MR__c,Authorized_Sign_Director_Operations__c,DateRB_Time__c,DateCB_Time__c,
                DateVB_Time__c,DateDO__c,Customer_Address__c,Total_Cost__c, Approved_By__c, Others__c From Cases__c WHERE Id = :caseId];
        system.debug('cases:'+cont);
        controller = new ApexPages.StandardSetController(cont);
        controller.setPageSize(1);
    }
    
    public PageReference pdf() {
        if (cont.isEmpty()) {
            return null; // No complaint to generate PDF
        }
        Cases__c cc = cont[0];
        
        PageReference pdfPage = Page.CustomerComplaintPDF;
        pdfPage.getParameters().put('id', cc.Id);
        blob pdfBlob;
        if(Test.isRunningTest()) { 
          pdfBlob = blob.valueOf('Unit.Test');
        } else {
          pdfBlob = pdfPage.getContentAsPDF();
        } 
        
        // Code to handle the PDF Blob, for example, save it or attach it to a record.
        
        return null; // Add your desired PageReference to redirect the user after generating the PDF.
    }
}