force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/spares__c/spares__c.object-meta.xml
<CustomObject>
    <label>Spare Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Spares Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/spares__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>M/C Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>RS/EA Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/Work_Order_for_Spares__c.object-meta.xml
<CustomObject>
    <label>WorkOrder</label>
    <nameField>
        <displayFormat>WorkOrder-{mm}{dd}-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Case__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rice Mill Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>CGST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Commissioning_Charges_for_each_machine__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges_for_each_machine__c</fullName>
    <label>Commissioning Charges for each machine</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <formula>Case__r.PhoneNumberNew__c+&apos;,&apos;+ Case__r.PhoneNumber2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <formula>Case__r.Customer_Name__c +&apos;,&apos;+ Case__r.CustomerName2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <defaultValue>0.001</defaultValue>
    <label>Forwarding Charges</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Forwarding_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges_Amount__c</fullName>
    <formula>Total_Price__c * Forwarding_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forwarding Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>Total__c +(CGST_amount__c )+(SGST_Amount__c )+( IGST_Amount__c )+( TCS__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <formula>Case__r.Account_Name__r.GSTIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GSTIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/HSN__c.field-meta.xml
<CustomField>
    <fullName>HSN__c</fullName>
    <label>HSN CODE</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>IGST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Issued_ON__c.field-meta.xml
<CustomField>
    <fullName>Issued_ON__c</fullName>
    <label>Issued ON</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Line_Items__c</fullName>
    <label>Line Items</label>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <formula>Case__r.Account_Name__r.Street__c+&apos;,&apos;+Case__r.Account_Name__r.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mill Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Packing_Charges__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges__c</fullName>
    <defaultValue>0.001</defaultValue>
    <label>Packing Charges</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Packing_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges_Amount__c</fullName>
    <formula>Total_Price__c * Packing_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packing Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Product_Machine_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Machine_Number__c</fullName>
    <formula>Case__r.Machine_No__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product/Machine Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>ProductCode</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Required_On__c.field-meta.xml
<CustomField>
    <fullName>Required_On__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Rice_Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Rice_Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rice Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>SGST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spare_Description__c.field-meta.xml
<CustomField>
    <fullName>Spare_Description__c</fullName>
    <label>Spare Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Case__r.Account_Name__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Total_Price__c + Packing_Charges_Amount__c + Forwarding_Charges_Amount__c + Commissioning_Charges_for_each_machine__c + Transit_Insurance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/WorkOrderSparesLine__c.object-meta.xml
<CustomObject>
    <label>Work Orders</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work OrdersLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <label>Contact Person Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <label>Mill Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Work_Order_for_Spares__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_for_Spares__c</fullName>
    <label>Work Order for Spares</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkOrderForSparesQuote.cls
public class WorkOrderForSparesQuote {
    
    private final Work_Order_for_Spares__c a; //object
    
    
    
    public String MstrId{GET;SET;}
    public String PDFNo{GET;SET;}
        public boolean show{get;set;}
    public boolean showpdf{get;set;}
    public List<Work_Order_for_Spares__c> Wosp { get; set; }
    
    
    public List<WorkOrderSparesLine__c> op { get; set; }
    public ApexPages.StandardSetController controller { get; set; }
    
    
    
    public PageReference Cancel()
    {
        PageReference Pdf = NEW PageReference('/'+MstrID);
        pdf.setredirect(TRUE);
        RETURN Pdf;
    }
    
    
    
    
    public WorkOrderForSparesQuote(ApexPages.StandardController stdcontroller) {
        Id workorderforsparesId = stdcontroller.getId();    
        Wosp = [SELECT 
                
                Spares_And_Machinery_Parts__r.id,
                
                Spares_And_Machinery_Parts__r.Unit__c,
                Spares_And_Machinery_Parts__r.Size__c,
                Spares_And_Machinery_Parts__r.Price__c,
                Spares_And_Machinery_Parts__r.MC_Name__c,
                Spares_And_Machinery_Parts__r.Name__c,
                Spares_And_Machinery_Parts__r.Order_Quantity__c,
                
                
                Account_Name__c,Batch_No__c,Case__c,CGST__c,
                Commissioning_Charges_for_each_machine__c,
                Contact_Person_Mobile_Number__c,Contact_Person_Name__c
                ,Date__c,
                Forwarding_Charges_Amount__c,Forwarding_Charges__c,
                Grand_Total__c,GSTIN__c,HSN__c,Id,IGST__c,
                Issued_ON__c,
                Line_Items__c,Mill_Address__c,
                Name,Packing_Charges_Amount__c,Packing_Charges__c,
                PAN_No__c,ProductCode__c,Product_Machine_Number__c,
                Quantity__c,Required_On__c,Rice_Mill_Name__c,SGST__c,Size__c,
                Spares_And_Machinery_Parts__c,Spare_Description__c,State__c,
                Status__c,Subject__c,SubTotal__c,tcs__c, Amt_In_words__c,
                Total_Price__c,Total__c,Transit_Insurance__c 
                FROM Work_Order_for_Spares__c
                
                
                
                
                WHERE id=:workorderforsparesId];
        
        controller = new ApexPages.StandardSetController(Wosp);
        controller.setPageSize(1);
        
        
        
        
        Set<Id> CasesIds = new Set<Id>(); 
        for (Work_Order_for_Spares__c WospRecord : Wosp) {
            CasesIds.add(WospRecord.Id);
        }        
        
        
        op=[SELECT Account_Name__c,Spares_And_Machinery_Parts__r.name,Available_Quantity__c,Cases__c,Contact_Person_Mobile_Number__c,
            Contact_Person_Name__c,Date__c,Diagram__c,Id,Issued_ON__c,MC_Name__c,Mill_Address__c,Discount__c,IGST_Amount__c,
            Name,Price__c,Product_Name__c,Quantity__c,Required_On_or_Before__c,Discount_Amount__c,
            Size__c,Spares_And_Machinery_Parts__c,Product_Code__c,Spare_Products__c,Sr_No__c,Status__c,Total_Price__c,TPrice__c,RS_SET__c,RS_EA__c,
            Work_Order_for_Spares__c FROM WorkOrderSparesLine__c
            
            WHERE Work_Order_for_Spares__c IN :CasesIds
           ]; 
        
        
        
        
        MstrId = ApexPages.currentPage().getParameters().get('id');
        
        
        
        
        
        for (WorkOrderSparesLine__c item : op) {
            System.debug('Spares_And_Machinery_Parts__r.Name value: ' +item.Spares_And_Machinery_Parts__r.Name);
            
            
        }                 
        
        for (Integer i = 0; i < op.size(); i++) {
            op[i].Sr_No__c = i + 1;}
        
    }
    
    
    
    
    
    
    
    
    

    //action method - returns a page reference
    public PageReference pdfAction() {   
        
        
        // Get PDF content from VF page
        PageReference pdfPage = Page.WorkorderQuote;
        pdfPage.getParameters().put('id',MstrId);
        Blob pdfBlob; //create a blob for the PDF content
        if (!Test.isRunningTest()) { //if we are not in testing context
            pdfBlob = pdfPage.getContent(); //generate the pdf blob
        } else { //otherwise, we are in testing context and getContent() gets funky so create the blob manually
            pdfBlob = Blob.valueOf('Some Text for a boring PDF file...');
        }      
        List<ContentDocumentLink> notesattch = [SELECT id, ContentDocument.Title,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: MstrID ORDER BY ContentDocument.Title ASC];    
        
        
        String FinalTitle = 'SpareQuotation'+notesattch.size();
        PDFNo=FinalTitle;
        // Create attachment and attach
        Attachment attach = new Attachment();
        attach.Body = pdfBlob;
        attach.Name = FinalTitle+'.pdf';
        attach.IsPrivate = false;
        attach.ParentId = MstrId;        
        attach.ContentType = 'application/pdf';
        insert attach; //insert the attachment
        
        // Redirect the user to object page
        
        //    PageReference destPage = new ApexPages.StandardController(Work_Order_for_Spares__c).view();
        
        PageReference Pdf = NEW PageReference('/'+MstrID);
        pdf.setredirect(TRUE);
        RETURN Pdf;
    }
    
    
 
    
     public PageReference pdfAction2() {   
        
        
        // Get PDF content from VF page
        PageReference pdfPage = Page.Workorder;
        pdfPage.getParameters().put('id',MstrId);
        Blob pdfBlob; //create a blob for the PDF content
        if (!Test.isRunningTest()) { //if we are not in testing context
            pdfBlob = pdfPage.getContent(); //generate the pdf blob
        } else { //otherwise, we are in testing context and getContent() gets funky so create the blob manually
            pdfBlob = Blob.valueOf('Some Text for a boring PDF file...');
        }      
        List<ContentDocumentLink> notesattch = [SELECT id, ContentDocument.Title,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: MstrID ORDER BY ContentDocument.Title ASC];    
        
        
        String FinalTitle = 'Workorder'+notesattch.size();
        PDFNo=FinalTitle;
        // Create attachment and attach
        Attachment attach = new Attachment();
        attach.Body = pdfBlob;
        attach.Name = FinalTitle+'.pdf';
        attach.IsPrivate = false;
        attach.ParentId = MstrId;        
        attach.ContentType = 'application/pdf';
        insert attach; //insert the attachment
        
        // Redirect the user to object page
        
        //    PageReference destPage = new ApexPages.StandardController(Work_Order_for_Spares__c).view();
        
        PageReference Pdf = NEW PageReference('/'+MstrID);
        pdf.setredirect(TRUE);
        RETURN Pdf;
    }
   
   
    
    
    
    
    
}