force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/spares__c/spares__c.object-meta.xml
<CustomObject>
    <label>Spare Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Spares Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/spares__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Diagram__c.field-meta.xml
<CustomField>
    <fullName>Diagram__c</fullName>
    <label>Drawing</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>M/C Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>RS/EA Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Required_On_or_Before__c.field-meta.xml
<CustomField>
    <fullName>Required_On_or_Before__c</fullName>
    <defaultValue>(Today() + 10)</defaultValue>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr. No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/Work_Order_for_Spares__c.object-meta.xml
<CustomObject>
    <label>WorkOrder</label>
    <nameField>
        <displayFormat>WorkOrder-{mm}{dd}-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Case__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rice Mill Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <formula>Case__r.PhoneNumberNew__c+&apos;,&apos;+ Case__r.PhoneNumber2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <formula>Case__r.Customer_Name__c +&apos;,&apos;+ Case__r.CustomerName2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Issued_ON__c.field-meta.xml
<CustomField>
    <fullName>Issued_ON__c</fullName>
    <label>Issued ON</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <formula>Case__r.Account_Name__r.Street__c+&apos;,&apos;+Case__r.Account_Name__r.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mill Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Product_Machine_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Machine_Number__c</fullName>
    <formula>Case__r.Machine_No__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product/Machine Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>ProductCode</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Required_On__c.field-meta.xml
<CustomField>
    <fullName>Required_On__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Rice_Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Rice_Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rice Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spare_Description__c.field-meta.xml
<CustomField>
    <fullName>Spare_Description__c</fullName>
    <label>Spare Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>In hold</fullName>
            </value>
            <value>
                <fullName>Cannot Be Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/SubTotal__c.field-meta.xml
<CustomField>
    <fullName>SubTotal__c</fullName>
    <label>SubTotal</label>
    <summarizedField>WorkOrderSparesLine__c.Quantity__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Basic Order Value</label>
    <summarizedField>WorkOrderSparesLine__c.TPrice__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/WorkOrderSparesLine__c.object-meta.xml
<CustomObject>
    <label>Work Orders</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work OrdersLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <label>Contact Person Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Diagram__c.field-meta.xml
<CustomField>
    <fullName>Diagram__c</fullName>
    <label>Diagram</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <label>Mill Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Required_On_or_Before__c.field-meta.xml
<CustomField>
    <fullName>Required_On_or_Before__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Spare_Products__c.field-meta.xml
<CustomField>
    <fullName>Spare_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spare Products</label>
    <referenceTo>SpareLineItem__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>Work_OrdersLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Work_Order_for_Spares__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_for_Spares__c</fullName>
    <label>Work Order for Spares</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkOrderForSpares.cls
public class WorkOrderForSpares {

public Id id { get; set; }
public List<Work_Order_for_Spares__c> Wosp { get; set; }

public Integer rowCount { get; set; }

public List<WorkOrderSparesLine__c> op { get; set; }
public ApexPages.StandardSetController controller { get; set; }


public WorkOrderForSpares(ApexPages.StandardController stdcontroller) {
           
         Id workorderforsparesId = stdcontroller.getId();    
         Wosp = [SELECT Account_Name__c,Case__c,
                 
                 Spares_And_Machinery_Parts__r.id,
                 Spares_And_Machinery_Parts__r.Name,
                 Spares_And_Machinery_Parts__r.Unit__c,
                 Spares_And_Machinery_Parts__r.Size__c,
                 Spares_And_Machinery_Parts__r.Price__c,
                 Spares_And_Machinery_Parts__r.MC_Name__c,
                   Spares_And_Machinery_Parts__r.Name__c,
                     Spares_And_Machinery_Parts__r.Order_Quantity__c,
                    
              
                Contact_Person_Mobile_Number__c,Contact_Person_Name__c,
                Date__c,Id,Issued_ON__c,Mill_Address__c,
                Name,OwnerId,ProductCode__c,Product_Machine_Number__c,Quantity__c,
                Required_On__c,Rice_Mill_Name__c,Spares_And_Machinery_Parts__c,
                Spare_Description__c,Status__c,Subject__c,SubTotal__c,Total_Price__c
        FROM Work_Order_for_Spares__c 
        WHERE id=:workorderforsparesId];
        
       controller = new ApexPages.StandardSetController(Wosp);
       controller.setPageSize(1);
        
       
     
         
          Set<Id> CasesIds = new Set<Id>(); 
           for (Work_Order_for_Spares__c WospRecord : Wosp) {
             CasesIds.add(WospRecord.Id);
        }        
      
         op=[SELECT Account_Name__c,Spares_And_Machinery_Parts__r.name,Available_Quantity__c,Cases__c,Contact_Person_Mobile_Number__c,
         Contact_Person_Name__c,Date__c,Diagram__c,Id,Issued_ON__c,MC_Name__c,Mill_Address__c,
         Name,Price__c,Product_Code__c,Product_Name__c,Quantity__c,Required_On_or_Before__c,
         Size__c,Spares_And_Machinery_Parts__c,Spare_Products__c,Sr_No__c,Status__c,Total_Price__c,
         Work_Order_for_Spares__c FROM WorkOrderSparesLine__c

         WHERE Work_Order_for_Spares__c IN :CasesIds
         ]; 
                 

      
      
        
           
                     
        for (WorkOrderSparesLine__c item : op) {
        System.debug('Spares_And_Machinery_Parts__r.Name value: ' +item.Spares_And_Machinery_Parts__r.Name);
        
       rowCount =0;
}                 
     
 for (Integer i = 0; i < op.size(); i++) {
          op[i].Sr_No__c = i + 1;}
        
    }

          public PageReference pdf() {
        if (wosp.isEmpty()) {
            return null; // No Quotes to generate PDF
    } 
 
      Work_Order_for_Spares__c wos = Wosp[0];
  
        PageReference pdfPage = Page.WorkorderQuote;
        pdfPage.getParameters().put('id', wos.Id);
                blob pdfBody;
        if(Test.isRunningTest()) { 
          pdfBody = blob.valueOf('Unit.Test');
        } else {
          pdfBody = pdfPage.getContentAsPDF();
        }
         PageReference pageRef = new PageReference('/' + wos.Id);
        pageRef.setRedirect(true);
        return pageRef;
          
    }

    
}