force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Authorised_Sign__c.field-meta.xml
<CustomField>
    <fullName>Authorised_Sign__c</fullName>
    <formula>IMAGE(&quot;/resource/CompanyLogo&quot;, &quot;Sign&quot;, 30, 70)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Authorised Sign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/C_C_Acknowledged_by__c.field-meta.xml
<CustomField>
    <fullName>C_C_Acknowledged_by__c</fullName>
    <label>C C Acknowledged by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Classification__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Classification__c</fullName>
    <label>Complaint Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Receipt_Date__c</fullName>
    <label>Complaint Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <formula>Account_Name__r.Street__c +&quot; &quot;+ Account_Name__r.Village__c +&quot; &quot;+ Account_Name__r.District__c +&quot; &quot;+ Account_Name__r.Area__r.Name +&quot; &quot;+ Account_Name__r.State__c +&quot; &quot;+ Account_Name__r.Country__c +&quot; &quot;+ Account_Name__r.Pincode__c</formula>
    <label>Customer Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerName2__c.field-meta.xml
<CustomField>
    <fullName>CustomerName2__c</fullName>
    <label>Customer Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerNameNew__c.field-meta.xml
<CustomField>
    <fullName>CustomerNameNew__c</fullName>
    <formula>Contact_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Designing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Designing_Cost__c</fullName>
    <label>Details of Designing Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Others__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Others__c</fullName>
    <label>Details of Others</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_QC_cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_QC_cost__c</fullName>
    <label>Details of QC cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Rework_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Rework_Cost__c</fullName>
    <label>Details of Rework Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Spares_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Spares_Cost__c</fullName>
    <label>Details of Spares Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Details_of_Transport_Cost__c.field-meta.xml
<CustomField>
    <fullName>Details_of_Transport_Cost__c</fullName>
    <label>Details of Transport Cost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Enclosures__c.field-meta.xml
<CustomField>
    <fullName>Enclosures__c</fullName>
    <label>Enclosures</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Engineer_Allotment_Date__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Allotment_Date__c</fullName>
    <label>Engineer Allotment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/IS_CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>IS_CAPA_Required__c</fullName>
    <label>IS CAPA Required ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_MFD__c.field-meta.xml
<CustomField>
    <fullName>Machine_MFD__c</fullName>
    <label>Machine MFD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_Name__c.field-meta.xml
<CustomField>
    <fullName>Machine_Name__c</fullName>
    <label>Machine Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine No.</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Cases (Machine No.)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Mill Name)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/ModeofReceipt__c.field-meta.xml
<CustomField>
    <fullName>ModeofReceipt__c</fullName>
    <label>Mode of Receipt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber2__c</fullName>
    <label>Phone Number 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumberNew__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumberNew__c</fullName>
    <formula>Account_Name__r.Mobile__c</formula>
    <label>Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Re_Occurance__c.field-meta.xml
<CustomField>
    <fullName>Re_Occurance__c</fullName>
    <label>Re-Occurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Service_Engineer__c</fullName>
    <label>Service Engineer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product / Machine Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Casescontroller.cls
public class Casescontroller {
    public Id id { get; set; }
    public List<Cases__c> cse { get; set; }
    // public Cases__c c { get; set; }
    public ApexPages.StandardSetController controller { get; set; }
    
    public Casescontroller(ApexPages.StandardController stdController) {
        Id caseId = stdController.getId();
        cse = [SELECT Id, Name, Mill_Name__c, Account_Name__r.Name,Machine_No__r.Name,Customer_Address__c, Customer_Name__c, Call_Type__c, 
               C_C_Acknowledged_by__c, Re_Occurance__c, Enclosures__c, CustomerNameNew__c, CustomerName2__c,  PhoneNumber2__c,
               Details_of_Designing_Cost__c, Details_of_Others__c, Details_of_QC_cost__c, Details_of_Rework_Cost__c, Details_of_Spares_Cost__c, Details_of_Transport_Cost__c,
               Complaint_Classification__c, Machine_Name__c, Complaint_Details__c, IS_CAPA_Required__c, Engineer_Allotment_Date__c,  
               Service_Engineer__c, Authorised_Sign__c, ModeofReceipt__c, Complaint_Receipt_Date__c, Machine_MFD__c, PhoneNumberNew__c From Cases__c WHERE Id = :caseId];
        system.debug('cases:'+cse);
        controller = new ApexPages.StandardSetController(cse);
        controller.setPageSize(1);
    }
    
    public PageReference pdf() {
        if (cse.isEmpty()) {
            return null; // No complaint to generate PDF
        }
        Cases__c ca = cse[0];
        
        PageReference pdfPage = Page.CustomerComplaintcommunicationPDF;
        pdfPage.getParameters().put('id', ca.Id);
         blob pdfBlob;
        if(Test.isRunningTest()) { 
          pdfBlob = blob.valueOf('Unit.Test');
        } else {
          pdfBlob = pdfPage.getContentAsPDF();
        } 
        
        // Code to handle the PDF Blob, for example, save it or attach it to a record.
        
        return null; // Add your desired PageReference to redirect the user after generating the PDF.
    }
}