force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Authorised_Sign__c.field-meta.xml
<CustomField>
    <fullName>Authorised_Sign__c</fullName>
    <formula>IMAGE(&quot;/resource/CompanyLogo&quot;, &quot;Sign&quot;, 30, 70)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Authorised Sign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/C_C_Acknowledged_by__c.field-meta.xml
<CustomField>
    <fullName>C_C_Acknowledged_by__c</fullName>
    <label>C C Acknowledged by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Classification__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Classification__c</fullName>
    <label>Complaint Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Receipt_Date__c</fullName>
    <label>Complaint Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <formula>Account_Name__r.Street__c +&quot; &quot;+ Account_Name__r.Village__c +&quot; &quot;+ Account_Name__r.District__c +&quot; &quot;+ Account_Name__r.Area__r.Name +&quot; &quot;+ Account_Name__r.State__c +&quot; &quot;+ Account_Name__r.Country__c +&quot; &quot;+ Account_Name__r.Pincode__c</formula>
    <label>Customer Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerName2__c.field-meta.xml
<CustomField>
    <fullName>CustomerName2__c</fullName>
    <label>Customer Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerNameNew__c.field-meta.xml
<CustomField>
    <fullName>CustomerNameNew__c</fullName>
    <formula>Contact_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Enclosures__c.field-meta.xml
<CustomField>
    <fullName>Enclosures__c</fullName>
    <label>Enclosures</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Engineer_Allotment_Date__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Allotment_Date__c</fullName>
    <label>Engineer Allotment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/IS_CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>IS_CAPA_Required__c</fullName>
    <label>IS CAPA Required ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Last_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Version_Number__c</fullName>
    <label>Last Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_MFD__c.field-meta.xml
<CustomField>
    <fullName>Machine_MFD__c</fullName>
    <label>Machine MFD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Mill Name)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/ModeofReceipt__c.field-meta.xml
<CustomField>
    <fullName>ModeofReceipt__c</fullName>
    <label>Mode of Receipt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber2__c</fullName>
    <label>Phone Number 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumberNew__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumberNew__c</fullName>
    <formula>Account_Name__r.Mobile__c</formula>
    <label>Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Re_Occurance__c.field-meta.xml
<CustomField>
    <fullName>Re_Occurance__c</fullName>
    <label>Re-Occurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Service_Engineer__c</fullName>
    <label>Service Engineer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcButtonControllercustcomplcomm.cls
public class LwcButtonControllercustcomplcomm {

    public Cases__c  comm{get;set;}

    public String currentRecordId{get;set;}

 

    public LwcButtonControllercustcomplcomm(){

        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

        if(currentRecordId != null && String.isNotBlank(currentRecordId)){

            comm = [SELECT Id, Name, Mill_Name__c, CustomerName2__c,  PhoneNumber2__c, Customer_Address__c, Customer_Name__c, Call_Type__c, C_C_Acknowledged_by__c, Re_Occurance__c, Enclosures__c, 
               Complaint_Classification__c, Complaint_Details__c, IS_CAPA_Required__c, Engineer_Allotment_Date__c,  CustomerNameNew__c,
               Service_Engineer__c, Authorised_Sign__c, ModeofReceipt__c, Complaint_Receipt_Date__c, Machine_MFD__c, PhoneNumberNew__c From Cases__c WHERE Id =:currentRecordId];

           

        }

        System.debug('Currentid: ' + currentRecordId);

    }

 

   

    @AuraEnabled

    public static String sendPdf(String recordId) {

        PageReference pdf = new pagereference('/apex/CustomerComplaintcommunicationPDF?id='+recordId);

        pdf.getParameters().put('id', recordId);

        System.debug('Recordid: ' + recordId);

        Blob body;

        try {

            // returns page as a PDF

            body = pdf.getContent();

        } catch (Exception e) {

            body = Blob.valueOf('data');

        }

 

        //insert content version
        
        ContentVersion CV = new ContentVersion();
        
        // Specify the PDF type
        String pdfType = 'Customer Complaint Communication';
        
        // Query existing ContentVersions for the same recordId and PDF type
        List<ContentVersion> existingVersions = [SELECT Id, Title FROM ContentVersion WHERE FirstPublishLocationId = :recordId AND Title LIKE :pdfType + '-%' ORDER BY CreatedDate DESC LIMIT 1];
        
        String versionLabel;
        Integer lastVersionNumber = 1; // Initialize with 1 by default
        
        if (!existingVersions.isEmpty()) {
            // If there are existing versions, determine the version label (S1, S2, etc.)
            String existingTitle = existingVersions[0].Title;
            
            // Extract the version number from the existing title
            try {
                String lastVersionLabel = existingTitle.substringAfter('V');
                lastVersionNumber = Integer.valueOf(lastVersionLabel);
                lastVersionNumber++;
            } catch (Exception e) {
                // Handle any exceptions if the existing title doesn't follow the expected format
            }
        }
        
        versionLabel = 'V' + lastVersionNumber;
        String uniqueNumber = pdfType + '-' + versionLabel;
        
        CV.Title = uniqueNumber;
        CV.PathOnClient = pdfType + '.pdf';
        CV.VersionData = body;
        CV.FirstPublishLocationId = recordId;
        
        insert CV;
        
        // Update the custom field on the Quote object to store the last version number for this PDF type
        if (!existingVersions.isEmpty()) {
            Cases__c cse = [SELECT Id, Last_Version_Number__c FROM Cases__c WHERE Id = :recordId LIMIT 1];
            cse.Last_Version_Number__c = lastVersionNumber;
            update cse;
        }

       

       /* Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();

        attach.setContentType('application/pdf');

        attach.setFileName('RiceTec CC Commnication.pdf');

        attach.Body = body;

 

        Cases__c cmail = [SELECT Email__c FROM Cases__c WHERE Id = :recordId];

 

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {cmail.Email__c});

        mail.setSubject(' PDF from RiceTec Machinery India Pvt. Ltd.,');

        mail.setHtmlBody('PDF for the Customer Complaint Communication');

        mail.setFileAttachments(new Messaging.EmailFileAttachment[] {attach});

        // Send the email

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});

        return 'Email sent Successfully with PDF.';*/
        return 'PDF saved successfully.';

   }

}