force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Accountant_Sign__c.field-meta.xml
<CustomField>
    <fullName>Accountant_Sign__c</fullName>
    <label>Accountant Sign.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <defaultValue>&quot;Managing Director&quot;</defaultValue>
    <label>Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/C_C_Acknowledged_by__c.field-meta.xml
<CustomField>
    <fullName>C_C_Acknowledged_by__c</fullName>
    <label>C C Acknowledged by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Classification__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Classification__c</fullName>
    <label>Complaint Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Complaint Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Details__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Details__c</fullName>
    <label>Complaint Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Complaint_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Receipt_Date__c</fullName>
    <label>Complaint Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Corrective_Action__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Action__c</fullName>
    <label>Corrective Action</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <formula>Account_Name__r.Street__c +&quot; &quot;+ Account_Name__r.Village__c +&quot; &quot;+ Account_Name__r.District__c +&quot; &quot;+ Account_Name__r.Area__r.Name +&quot; &quot;+ Account_Name__r.State__c +&quot; &quot;+ Account_Name__r.Country__c +&quot; &quot;+ Account_Name__r.Pincode__c</formula>
    <label>Customer Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerName2__c.field-meta.xml
<CustomField>
    <fullName>CustomerName2__c</fullName>
    <label>Customer Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/CustomerNameNew__c.field-meta.xml
<CustomField>
    <fullName>CustomerNameNew__c</fullName>
    <formula>Contact_Name__c</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date_of_Commissioning__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Commissioning__c</fullName>
    <label>Date of Commissioning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date_of_Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Dispatch__c</fullName>
    <label>Date of Dispatch</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Datec__c.field-meta.xml
<CustomField>
    <fullName>Datec__c</fullName>
    <inlineHelpText>Corrective Action</inlineHelpText>
    <label>(CA)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Datep__c.field-meta.xml
<CustomField>
    <fullName>Datep__c</fullName>
    <inlineHelpText>Preventive Action</inlineHelpText>
    <label>(PA)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Debit_Note_No__c.field-meta.xml
<CustomField>
    <fullName>Debit_Note_No__c</fullName>
    <label>Debit Note No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Designinig_cost__c.field-meta.xml
<CustomField>
    <fullName>Designinig_cost__c</fullName>
    <label>Designinig cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Enclosures__c.field-meta.xml
<CustomField>
    <fullName>Enclosures__c</fullName>
    <label>Enclosures</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Initial_DC_No__c.field-meta.xml
<CustomField>
    <fullName>Initial_DC_No__c</fullName>
    <label>Initial DC No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/IS_CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>IS_CAPA_Required__c</fullName>
    <label>IS CAPA Required ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Last_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Version_Number__c</fullName>
    <label>Last Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine No.</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Cases (Machine No.)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/ModeofReceipt__c.field-meta.xml
<CustomField>
    <fullName>ModeofReceipt__c</fullName>
    <label>Mode of Receipt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Obsesrvations_status_QC__c.field-meta.xml
<CustomField>
    <fullName>Obsesrvations_status_QC__c</fullName>
    <label>Obsesrvations status(QC)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Others__c.field-meta.xml
<CustomField>
    <fullName>Others__c</fullName>
    <label>Others</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/PhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber2__c</fullName>
    <label>Phone Number 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Prepared_By__c.field-meta.xml
<CustomField>
    <fullName>Prepared_By__c</fullName>
    <defaultValue>&quot;Incharge - Service&quot;</defaultValue>
    <label>Prepared By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Preventive_Action__c.field-meta.xml
<CustomField>
    <fullName>Preventive_Action__c</fullName>
    <label>Preventive Action</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/QC_cost__c.field-meta.xml
<CustomField>
    <fullName>QC_cost__c</fullName>
    <label>QC cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/QC_Sign__c.field-meta.xml
<CustomField>
    <fullName>QC_Sign__c</fullName>
    <label>QC Sign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Re_Occurance__c.field-meta.xml
<CustomField>
    <fullName>Re_Occurance__c</fullName>
    <label>Re-Occurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Returnable_DC_No__c.field-meta.xml
<CustomField>
    <fullName>Returnable_DC_No__c</fullName>
    <label>Returnable DC No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_By__c</fullName>
    <defaultValue>&quot;Director - Operations&quot;</defaultValue>
    <label>Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_CBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_CBy__c</fullName>
    <label>(Corrective Action)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_PBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_PBy__c</fullName>
    <label>(Preventive Action)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Reviewed_RBy__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_RBy__c</fullName>
    <label>(Root Cause)Reviewed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Rework_Cost__c.field-meta.xml
<CustomField>
    <fullName>Rework_Cost__c</fullName>
    <label>Rework Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <label>Root Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Sl_No__c.field-meta.xml
<CustomField>
    <fullName>Sl_No__c</fullName>
    <label>Sl. No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Spares_cost__c.field-meta.xml
<CustomField>
    <fullName>Spares_cost__c</fullName>
    <label>Spares cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Stores_GRN_No__c.field-meta.xml
<CustomField>
    <fullName>Stores_GRN_No__c</fullName>
    <label>Stores GRN No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Stores_Signature__c.field-meta.xml
<CustomField>
    <fullName>Stores_Signature__c</fullName>
    <label>Stores Signature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Transport_Cost__c.field-meta.xml
<CustomField>
    <fullName>Transport_Cost__c</fullName>
    <label>Transport Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Verified_Results__c.field-meta.xml
<CustomField>
    <fullName>Verified_Results__c</fullName>
    <label>Verified Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LwcButtonControllercustcomplaint.cls
public class LwcButtonControllercustcomplaint {

    public Cases__c  complaint{get;set;}

    public String currentRecordId{get;set;}

 

    public LwcButtonControllercustcomplaint(){

        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

        if(currentRecordId != null && String.isNotBlank(currentRecordId)){

            complaint = [SELECT Id,Name, Customer_Address__c,Stores_GRN_No__c,Returnable_DC_No__c,Initial_DC_No__c,Sl_No__c,    
                ModeofReceipt__c,Complaint_Receipt_Date__c,Date_of_Dispatch__c,Date_of_Commissioning__c, CustomerNameNew__c,
                Machine_No__c, Complaint_Date__c, Enclosures__c, Complaint_Details__c, Reviewed_CBy__c, Reviewed_RBy__c,
                Reviewed_PBy__c,Preventive_Action__c,Root_Cause__c,Date__c,Stores_Signature__c,Datep__c,Datec__c, 
                IS_CAPA_Required__c,Re_Occurance__c,C_C_Acknowledged_by__c,Accountant_Sign__c,Debit_Note_No__c, CustomerName2__c,  PhoneNumber2__c,
                Debit_Note_Date__c,QC_Sign__c,Designinig_cost__c,Rework_Cost__c,Spares_cost__c,Obsesrvations_status_QC__c,  
                QC_cost__c, Transport_Cost__c,Prepared_By__c,Reviewed_By__c,Verified_Results__c,Corrective_Action__c, 
                Complaint_Classification__c,Approved_By__c, Others__c From Cases__c WHERE Id =:currentRecordId];

           

        }

        System.debug('Currentid: ' + currentRecordId);

    }

 

   

    @AuraEnabled

    public static String sendPdf(String recordId) {

        PageReference pdf = new pagereference('/apex/CustomerComplaintPDF?id='+recordId);

        pdf.getParameters().put('id', recordId);

        System.debug('Recordid: ' + recordId);

        Blob body;

        try {

            // returns page as a PDF

            body = pdf.getContent();

        } catch (Exception e) {

            body = Blob.valueOf('data');

        }

 

        //insert content version
        
        ContentVersion CV = new ContentVersion();
        
        // Specify the PDF type
        String pdfType = 'Customer Complaint';
        
        // Query existing ContentVersions for the same recordId and PDF type
        List<ContentVersion> existingVersions = [SELECT Id, Title FROM ContentVersion WHERE FirstPublishLocationId = :recordId AND Title LIKE :pdfType + '-%' ORDER BY CreatedDate DESC LIMIT 1];
        
        String versionLabel;
        Integer lastVersionNumber = 1; // Initialize with 1 by default
        
        if (!existingVersions.isEmpty()) {
            // If there are existing versions, determine the version label (S1, S2, etc.)
            String existingTitle = existingVersions[0].Title;
            
            // Extract the version number from the existing title
            try {
                String lastVersionLabel = existingTitle.substringAfter('V');
                lastVersionNumber = Integer.valueOf(lastVersionLabel);
                lastVersionNumber++;
            } catch (Exception e) {
                // Handle any exceptions if the existing title doesn't follow the expected format
            }
        }
        
        versionLabel = 'V' + lastVersionNumber;
        String uniqueNumber = pdfType + '-' + versionLabel;
        
        CV.Title = uniqueNumber;
        CV.PathOnClient = pdfType + '.pdf';
        CV.VersionData = body;
        CV.FirstPublishLocationId = recordId;
        
        insert CV;
        
        // Update the custom field on the Quote object to store the last version number for this PDF type
        if (!existingVersions.isEmpty()) {
            Cases__c cse = [SELECT Id, Last_Version_Number__c FROM Cases__c WHERE Id = :recordId LIMIT 1];
            cse.Last_Version_Number__c = lastVersionNumber;
            update cse;
        }

       

        /*Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();

        attach.setContentType('application/pdf');

        attach.setFileName('RiceTec Customer Complaint.pdf');

        attach.Body = body;

 

        Cases__c cemail = [SELECT Email__c FROM Cases__c WHERE Id = :recordId];

 

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {cemail.Email__c});

        mail.setSubject('PDF from RiceTec Machinery India Pvt. Ltd.,');

        mail.setHtmlBody('PDF for the Customer Complaint');

        mail.setFileAttachments(new Messaging.EmailFileAttachment[] {attach});

        // Send the email

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});

        return 'Email sent Successfully with PDF.'; */
    return 'PDF saved successfully.';
   }

}