force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine No.</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Cases (Machine No.)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Spares__c.field-meta.xml
<CustomField>
    <fullName>Spares__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/SpareLineItem__c.object-meta.xml
<CustomObject>
    <label>Spare Products</label>
    <nameField>
        <label>Spare Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spare Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SpareLineItem__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>SpareLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Dept__c.field-meta.xml
<CustomField>
    <fullName>Dept__c</fullName>
    <label>Dept</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/RS_EA__c.field-meta.xml
<CustomField>
    <fullName>RS_EA__c</fullName>
    <label>RS/EA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Spare_Description_of_Material__c.field-meta.xml
<CustomField>
    <fullName>Spare_Description_of_Material__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>SpareLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Std_Qty__c.field-meta.xml
<CustomField>
    <fullName>Std_Qty__c</fullName>
    <label>Std Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/spares__c.object-meta.xml
<CustomObject>
    <label>Spare Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Spares Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/spares__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Dept__c.field-meta.xml
<CustomField>
    <fullName>Dept__c</fullName>
    <label>Dept</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Diagram__c.field-meta.xml
<CustomField>
    <fullName>Diagram__c</fullName>
    <label>Drawing</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Machine_No__c.field-meta.xml
<CustomField>
    <fullName>Machine_No__c</fullName>
    <formula>Cases__r.Machine_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Machine No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>M/C Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>RS/EA Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Required_On_or_Before__c.field-meta.xml
<CustomField>
    <fullName>Required_On_or_Before__c</fullName>
    <defaultValue>(Today() + 10)</defaultValue>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/SpareDescriptionofMaterial__c.field-meta.xml
<CustomField>
    <fullName>SpareDescriptionofMaterial__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/SpareLineItem__c.field-meta.xml
<CustomField>
    <fullName>SpareLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SpareLineItem</label>
    <referenceTo>SpareLineItem__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr. No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Std_Qty__c.field-meta.xml
<CustomField>
    <fullName>Std_Qty__c</fullName>
    <label>Std Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Product2WorkorderRetrieving.cls
public with sharing class Product2WorkorderRetrieving {
   
    @AuraEnabled()
            public static List<spares__c> retrieveProducts(){
                return [ SELECT Available_Quantity__c,Cases__c,Dept__c,Diagram__c,
                        Id,MC_Name__c,Name,Name__c,Order_Quantity__c,Price__c,Cases__r.Machine_No__c,
                        Product_Code__c,Size__c,SpareDescriptionofMaterial__c,Discount__C,
                        SpareLineItem__c,Spares_And_Machinery_Parts__c,Sr_No__c,Std_Qty__c,Required_On_or_Before__c,
                        Unit_Type__c,Unit__c FROM spares__c
 
                ];
            }
            
            public class ProductUpdateWrapper {
                @AuraEnabled public String Id;
                @AuraEnabled public String CaseId; 
            }
              
     @AuraEnabled
            public static void updateProductOpport(List<String> selectedProductIds, Id CaseId) {
      try {
                    List<SpareLineItem__c> WorkOrderSparesLineItemsToInsert = new List<SpareLineItem__c>();
                    
                 for (spares__c product : [SELECT Available_Quantity__c,Cases__c,Dept__c,Diagram__c,Id,
                                           MC_Name__c,Name,Name__c,Order_Quantity__c,Price__c,Product_Code__c,
                                           Size__c,SpareDescriptionofMaterial__c,Discount__C,
                                           Spares_And_Machinery_Parts__c,Sr_No__c,Std_Qty__c,Unit_Type__c,Required_On_or_Before__c,
                                           Unit__c 
                                           FROM spares__c
                                           WHERE Id IN :selectedProductIds]) {
                                               
                        SpareLineItem__c  lineItem = new SpareLineItem__c(
                                cases__c = CaseId,
                                Spares_And_Machinery_Parts__c = product.Id,
                                Name=product.name,
                                MC_Name__c=product.MC_Name__c,
                                Diagram__c = product.Diagram__c,
                                Product_Code__c = product.Product_Code__c,
                                Spare_Description_of_Material__c=product.SpareDescriptionofMaterial__c,
                                Size__c=product.Size__c,
                                Dept__c=product.Dept__c,
                                Units__c=product.Unit__c,
                                Std_Qty__c=product.Std_Qty__c,
                                RS_EA__c=product.Price__c,
                               Discount__C=Product.Discount__C,
                               Required_On_or_Before__c=product.Required_On_or_Before__c                                               
                                );
                     WorkOrderSparesLineItemsToInsert.add(lineItem);                      
                    }

                if (!WorkOrderSparesLineItemsToInsert.isEmpty()) {
                insert WorkOrderSparesLineItemsToInsert;
                system.debug('lineitems'+WorkOrderSparesLineItemsToInsert);	
            }
        } 
                catch (Exception e) {
            // Handle the exception appropriately
           System.debug('Exception: ' + e.getMessage());
        }
     }  
 }