force-app/main/default/objects/Cases__c/Cases__c.object-meta.xml
<CustomObject>
    <label>Cases</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cases__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Root Cause</inlineHelpText>
    <label>(RC)Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cases__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product / Machine Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Products__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Products__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quoted_Price__c - Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/SpareLineItem__c.object-meta.xml
<CustomObject>
    <label>Spare Products</label>
    <nameField>
        <label>Spare Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spare Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SpareLineItem__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>SpareLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>SpareLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpareLineItem__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Final_Price__c*Units__c</formula>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/Work_Order_for_Spares__c.object-meta.xml
<CustomObject>
    <label>WorkOrder</label>
    <nameField>
        <displayFormat>WorkOrder-{mm}{dd}-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Case__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rice Mill Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <formula>Case__r.PhoneNumberNew__c+&apos;,&apos;+ Case__r.PhoneNumber2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <formula>Case__r.Customer_Name__c +&apos;,&apos;+ Case__r.CustomerName2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Issued_ON__c.field-meta.xml
<CustomField>
    <fullName>Issued_ON__c</fullName>
    <label>Issued ON</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <formula>Case__r.Account_Name__r.Street__c+&apos;,&apos;+Case__r.Account_Name__r.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mill Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>In hold</fullName>
            </value>
            <value>
                <fullName>Cannot Be Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Basic Order Value</label>
    <summarizedField>WorkOrderSparesLine__c.TPrice__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/WorkOrderSparesLine__c.object-meta.xml
<CustomObject>
    <label>Work Orders</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work OrdersLineItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Cases__c.field-meta.xml
<CustomField>
    <fullName>Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cases</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <label>Contact Person Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Diagram__c.field-meta.xml
<CustomField>
    <fullName>Diagram__c</fullName>
    <label>Diagram</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>MC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <label>Mill Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Spare Description of Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Required_On_or_Before__c.field-meta.xml
<CustomField>
    <fullName>Required_On_or_Before__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Spare_Products__c.field-meta.xml
<CustomField>
    <fullName>Spare_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spare Products</label>
    <referenceTo>SpareLineItem__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>Work_OrdersLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderSparesLine__c/fields/Work_Order_for_Spares__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_for_Spares__c</fullName>
    <label>Work Order for Spares</label>
    <referenceTo>Work_Order_for_Spares__c</referenceTo>
    <relationshipLabel>Work OrdersLineItem</relationshipLabel>
    <relationshipName>WorkOrderSparesLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Redirect_Main.cls
/* public class Redirect_Main {
public List<WorkOrderSparesLine__c> accs { get; set; }
public List<Work_Order_for_Spares__c> qList{ get; set; }
public List<SpareLineItem__c> op{ get; set; }
public Redirect_Main(ApexPages.StandardController controller) {
         
         
         List<id> cnt = new List<id>();
for(Work_Order_for_Spares__c c : [Select case__c from Work_Order_for_Spares__c]) {
         cnt.add(c.case__c);
}

        List<WorkOrderSparesLine__c> accs = [SELECT Account_Name__c,Available_Quantity__c,
        Cases__c,Contact_Person_Mobile_Number__c,Contact_Person_Name__c,
        Date__c,Diagram__c,Id,Issued_ON__c,MC_Name__c,Mill_Address__c,
        Name,Price__c,Products__c,Product_Code__c,Product_Name__c,Quantity__c,Required_On_or_Before__c,
        Size__c,Spares_And_Machinery_Parts__c,Spare_Products__c,Sr_No__c,Status__c,
        Total_Price__c,Work_Order_for_Spares__c 
        FROM WorkOrderSparesLine__c 
        where Cases__c IN: cnt
        ];  
       
    }    
}

*/



public class Redirect_Main {
public List<Work_Order_for_Spares__c> op { get; set; }

public List<WorkOrderSparesLine__c> accs{ get; set; }
public Redirect_Main(ApexPages.StandardController controller) {
List<String> cnt = new List<String>();
for(Work_Order_for_Spares__c c : [Select Id,name,Case__c From Work_Order_for_Spares__c limit 1]) {
         cnt.add(c.Id);
         

       accs= [SELECT Account_Name__c,Available_Quantity__c,
        Cases__c,Contact_Person_Mobile_Number__c,Contact_Person_Name__c,
        Date__c,Diagram__c,Id,Issued_ON__c,MC_Name__c,Mill_Address__c,
        Name,Price__c,Product_Code__c,Quantity__c,Required_On_or_Before__c,
        Size__c,Spares_And_Machinery_Parts__c,Spare_Products__c,Sr_No__c,Status__c,
        Total_Price__c,Work_Order_for_Spares__c 
        FROM WorkOrderSparesLine__c 
        where Work_Order_for_Spares__c IN: cnt];

 }
 }
 }