force-app/main/default/objects/spares__c/spares__c.object-meta.xml
<CustomObject>
    <label>Spare Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Spares Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/spares__c/fields/MC_Name__c.field-meta.xml
<CustomField>
    <fullName>MC_Name__c</fullName>
    <label>M/C Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>RS/EA Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Spares_And_Machinery_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/spares__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/Work_Order_for_Spares__c.object-meta.xml
<CustomObject>
    <label>WorkOrder</label>
    <nameField>
        <displayFormat>WorkOrder-{mm}{dd}-{000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Case__r.Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rice Mill Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Cases__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Mobile_Number__c</fullName>
    <formula>Case__r.PhoneNumberNew__c+&apos;,&apos;+ Case__r.PhoneNumber2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <formula>Case__r.Customer_Name__c +&apos;,&apos;+ Case__r.CustomerName2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Person Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Issued_ON__c.field-meta.xml
<CustomField>
    <fullName>Issued_ON__c</fullName>
    <label>Issued ON</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Mill_Address__c.field-meta.xml
<CustomField>
    <fullName>Mill_Address__c</fullName>
    <formula>Case__r.Account_Name__r.Street__c+&apos;,&apos;+Case__r.Account_Name__r.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mill Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Product_Machine_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Machine_Number__c</fullName>
    <formula>Case__r.Machine_No__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product/Machine Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>ProductCode</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Required_On__c.field-meta.xml
<CustomField>
    <fullName>Required_On__c</fullName>
    <label>Required On or Before</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Rice_Mill_Name__c.field-meta.xml
<CustomField>
    <fullName>Rice_Mill_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rice Mill Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spare_Description__c.field-meta.xml
<CustomField>
    <fullName>Spare_Description__c</fullName>
    <label>Spare Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Spares_And_Machinery_Parts__c.field-meta.xml
<CustomField>
    <fullName>Spares_And_Machinery_Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spares And Machinery Parts</label>
    <referenceTo>spares__c</referenceTo>
    <relationshipName>Work_Order_for_Spares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>In hold</fullName>
            </value>
            <value>
                <fullName>Cannot Be Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/SubTotal__c.field-meta.xml
<CustomField>
    <fullName>SubTotal__c</fullName>
    <label>SubTotal</label>
    <summarizedField>WorkOrderSparesLine__c.Quantity__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Work_Order_for_Spares__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Basic Order Value</label>
    <summarizedField>WorkOrderSparesLine__c.TPrice__c</summarizedField>
    <summaryForeignKey>WorkOrderSparesLine__c.Work_Order_for_Spares__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/WorkPreviewController.cls
public class WorkPreviewController {
    
    public String MstrId{get;set;}
    public Work_Order_for_Spares__c accObj{get;set;}
    
    public String PDFNo{get;set;}
    public String EFNo{get;set;}
    public boolean show{get;set;}
    public boolean showpdf{get;set;}
    public ApexPages.PageReference page2{get;set;}
    
    
    public PageReference Cancel()
    {
        PageReference Pdf = new PageReference('/'+MstrID);
        pdf.setredirect(True);
        return Pdf;
    }
    
    public WorkPreviewController(ApexPages.StandardController Controller){
        MstrId = ApexPages.currentPage().getParameters().get('id');
        accObj = [SELECT Account_Name__c,Case__c,
                 
                 Spares_And_Machinery_Parts__r.id,
                 Spares_And_Machinery_Parts__r.Name,
                 Spares_And_Machinery_Parts__r.Unit__c,
                 Spares_And_Machinery_Parts__r.Size__c,
                 Spares_And_Machinery_Parts__r.Price__c,
                 Spares_And_Machinery_Parts__r.MC_Name__c,
                   Spares_And_Machinery_Parts__r.Name__c,
                     Spares_And_Machinery_Parts__r.Order_Quantity__c,
                    
              
                Contact_Person_Mobile_Number__c,Contact_Person_Name__c,
                Date__c,Id,Issued_ON__c,Mill_Address__c,
                Name,OwnerId,ProductCode__c,Product_Machine_Number__c,Quantity__c,
                Required_On__c,Rice_Mill_Name__c,Spares_And_Machinery_Parts__c,
                Spare_Description__c,Status__c,Subject__c,SubTotal__c,Total_Price__c
        FROM Work_Order_for_Spares__c 
         Where id =: MstrId ];
        //WHERE id=:workorderforsparesId
    }
    
    
    
    public PageReference pdfAction()
    {
        PageReference savepage ;
        savepage = Page.WorkOrderPreview;
        savepage.getParameters().put('id',MstrID);
        system.debug('id:- '+MstrID);
        blob pdfBlob;
        if (!Test.isRunningTest()) {
            pdfBlob = savepage.getContent(); //generate the pdf blob
        } else { 
            pdfBlob = Blob.valueOf('Test');
        }
        List<ContentDocumentLink> notesattch = [select id, ContentDocument.Title,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: MstrID order by ContentDocument.Title asc];    
        system.debug('notesattch## ' + notesattch);
        if(notesattch.size() > 0)
        {
            string title =  notesattch[0].ContentDocument.Title;
            system.debug('title111 ' + title);
            List<String> titleSplit = title.split('R');
            //String FinalTitle = titleSplit[0]+'R0'+notesattch.size();
            String FinalTitle = 'R0'+notesattch.size();
            system.debug('FinalTitle22 ' + FinalTitle);
            PDFNo=FinalTitle;
            
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
            conVer.PathOnClient = FinalTitle+'.pdf'; 
            conVer.Title = FinalTitle; 
            conVer.VersionData = pdfBlob;
            system.debug('conVer@@ ' + conVer);
            insert conVer;  
            
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = MstrID;
            conDocLink.ContentDocumentId = conDoc; 
            conDocLink.shareType = 'V';
            insert conDocLink;
            update accObj;
            
            show=false;
            showpdf=true;
            PageReference savepage2 = Page.WorkOrderPreview;
            savepage2.getParameters().put('id',MstrID);
            if(!show)
                savepage2.getParameters().put('show','0');
            savepage2.setRedirect(true);
            return savepage2;
            
        }
        
        
        {
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
            conVer.PathOnClient = PDFNo+'.pdf'; 
            conVer.Title = PDFNo; 
            conVer.VersionData = pdfBlob;
            insert conVer;  
            
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = MstrID;
            conDocLink.ContentDocumentId = conDoc; 
            conDocLink.shareType = 'V';
            insert conDocLink;
            //Addtext = 'File Attached';
            
            update accObj;
           
            show=false;
            showpdf=true;
            PageReference savepage2 = Page.WorkOrderPreview;//Cafactionpage;CAFFormPDF
            savepage2.getParameters().put('id',MstrID);
            if(!show)
                savepage2.getParameters().put('show','0');
            savepage2.setRedirect(true);
            return savepage2;
        }
        
        //PageReference Pdf = new PageReference('/'+MstrID);
        //pdf.setredirect(True);
        //return Pdf;        
        
    }
    
}