force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/FinalF__c.field-meta.xml
<CustomField>
    <fullName>FinalF__c</fullName>
    <formula>IF(
    NOT(Discounted_Unit_Price__c==0),
      Discounted_Unit_Price__c * Quantity__c,
    Calculated_Unit_Price__c * Quantity__c
   
    
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/PowerHP__c.field-meta.xml
<CustomField>
    <fullName>PowerHP__c</fullName>
    <label>Power in HP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/QuotedQ__c.field-meta.xml
<CustomField>
    <fullName>QuotedQ__c</fullName>
    <formula>Unit_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quoted Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quotes__c.field-meta.xml
<CustomField>
    <fullName>Quotes__c</fullName>
    <label>Quotes</label>
    <referenceTo>Quotes__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/FINAL_SUB_COST__c.field-meta.xml
<CustomField>
    <fullName>FINAL_SUB_COST__c</fullName>
    <label>FINAL SUB COST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/QUOTED_SUB_COST__c.field-meta.xml
<CustomField>
    <fullName>QUOTED_SUB_COST__c</fullName>
    <label>QUOTED SUB COST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Total_Power_Required__c.field-meta.xml
<CustomField>
    <fullName>Total_Power_Required__c</fullName>
    <label>Total Power Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SumCosts.cls
public class SumCosts {
    public static void CostMethod(List<Quote_Line_Item__c> oppolist,List<Quote_Line_Item__c> oldList){
        set<id>Ids = new Set<id>();
        if(oppolist!=null){
        for(Quote_Line_Item__c op:oppolist){
            Ids.add(op.Quotes__c);
        }   
        }
        if(oldList!=null){
        for(Quote_Line_Item__c sp:oldList){
            Ids.add(sp.Quotes__c);
        }   
        }
        List<Quotes__c> prodList = [SELECT Id, Name, QUOTED_SUB_COST__c, FINAL_SUB_COST__c, Total_Power_Required__c,(SELECT Id, Name, PowerHP__c, QuotedQ__c, FinalF__c FROM Quote_Line_Items__r) FROM Quotes__c WHERE id=:Ids];
         Double SumOfQuotedPrice=0;
         Double SumOfFinalPrice=0;
         Double SumOfTotalPower=0;
        If(prodList!=null){
        for(Quotes__c opp:prodList){
            for(Quote_Line_Item__c p:opp.Quote_Line_Items__r){
                if(p.QuotedQ__c!=null){
            SumOfQuotedPrice = SumOfQuotedPrice+p.QuotedQ__c;
                }
                if(p.FinalF__c!=null){
            SumOfFinalPrice = SumOfFinalPrice+p.FinalF__c;
            }
               if(p.PowerHP__c!=null){
            SumOfTotalPower = SumOfTotalPower+p.PowerHP__c;
            }  
            }
             opp.QUOTED_SUB_COST__c = SumOfQuotedPrice;
             opp.FINAL_SUB_COST__c = SumOfFinalPrice;
             opp.Total_Power_Required__c = SumOfTotalPower;
            
        }
        }
       database.update(prodList, false);
    }
}