force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O - {00000}</displayFormat>
        <label>Order No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Building_No_Street__c.field-meta.xml
<CustomField>
    <fullName>Building_No_Street__c</fullName>
    <label>Building No. &amp; Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>CGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Sub_Total__c * CGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Commissioning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Commissioning Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Amount__c</fullName>
    <formula>Sub_Total__c  +  CGST_Amount__c  +  IGST_Amount__c  +  SGST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Proforma_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proforma Invoice</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>SGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>Package_Charges__c  +  Forwarding_Charge__c  +  Commissioning_Charges__c  +  Engineering_Charges__c  +  Transportation_Charges__c  +  Transit_Insurance_Amount__c + Basic_Order_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI---{0000000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice</label>
    <nameField>
        <displayFormat>I - {000000}</displayFormat>
        <label>Proforma Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/fields/Building_No_Street__c.field-meta.xml
<CustomField>
    <fullName>Building_No_Street__c</fullName>
    <label>Building No. &amp; Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>CGST%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Total_Charges__c * CGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <defaultValue>0.01</defaultValue>
    <label>Forwarding Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Grand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Amount__c</fullName>
    <formula>Total_Charges__c  +   GST_Amount__c +  Insurance_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>IGST%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>IF( AND(SGST_Amount__c == 0,CGST_Amount__c == 0) , Total_Charges__c * GST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>0.001</defaultValue>
    <label>Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Amount__c</fullName>
    <formula>Total_Charges__c *  Insurance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>Inv-{0000000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Proforma Invoice</relationshipLabel>
    <relationshipName>Proforma_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Packing_Charges__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges__c</fullName>
    <defaultValue>0.01</defaultValue>
    <label>Packing Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Total_Charges__c.field-meta.xml
<CustomField>
    <fullName>Total_Charges__c</fullName>
    <formula>Sub_Total__c   +   Forwarding_Charges_Amount__c   +   Commissioning_Charges__c    + Packing_Charges_Amount__c</formula>
    <label>Total Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <formula>IF( OR( BillingStateProvince__c == &apos;Telangana&apos;, BillingStateProvince__c == &apos;telangana&apos;, BillingStateProvince__c == &apos;TELANGANA&apos;), 0.09, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Commissioning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Commissioning Charges For Each Machine</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <label>Forwarding Charges (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Forwarding_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges_Amount__c</fullName>
    <formula>QuotedQQ__c *  Forwarding_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forwarding Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>18</fullName>
                <default>true</default>
                <label>18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>Total_Cost__c   *  VALUE( TEXT( GST__c ) )  / 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Packing_Charges__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges__c</fullName>
    <label>Packing Charges (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Packing_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Packing_Charges_Amount__c</fullName>
    <formula>QuotedQQ__c   *  Packing_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packing Charges Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Proforma_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proforma Invoice</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Village__c</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Invoice.cls
public class Invoice {
    public Id id { get; set; }
    public List<Proforma_Invoice__c> InvoiceList { get; set; }
    public List<Quote_Line_Item__c> QLI {get;set;}
    public List<Order_Line_Item__c>ORDL{get;set;}
    public Integer currentPageIndex { get; set; }
    public Integer totalPages { get; set; }
    
    public Invoice(ApexPages.StandardController controller) {
        id = controller.getId();
        InvoiceList = [SELECT Id,Total_Charges__c,State__c,
                       Customer_Name__c,Village__c,
                       Total_Amount__c,Sub_Total__c,Name,
                       Packing_Charges_Amount__c,
                       Packing_Charges__c,Orders__c,Invoice_Number__c,
                       Insurance_Amount__c,Insurance__c,GST_Amount__c,
                       GST__c,Grand_Amount__c,Forwarding_Charges_Amount__c,
                       Forwarding_Charges__c,District__c,Country__c,
                       Commissioning_Charges__c,City__c,CGST__c,CGST_Amount__c,
                       Building_No_Street__c,Amount_Received__c,SGST__c,SGST_Amount__c,
                       Balance_Amount__c FROM Proforma_Invoice__c WHERE id = :id];
        			   totalPages = InvoiceList.size();
             		   currentPageIndex = 0;
        totalPages = InvoiceList.size();
             currentPageIndex = 0;
    
        QLI = [SELECT Product_Name__c,Category1__c, Quantity__c, Final_Price_Final_Price__c, Unit_Price__c, RowNumber__c
    FROM Quote_Line_Item__c WHERE Quotes__r.Proforma_Invoice__c = :id];
        
        for (INTEGER I = 0; I < QLI.size(); I++) {
            QLI[I].RowNumber__c = I + 1;
        }
        ORDL = [SELECT Name,Orders__r.Name, Productes__r.Products__c,Product_Description__c, Quantity__c, Final_Price_After_Discount__c, Unit_Rate__c, Value__c,Serial_No__c,Orders__r.Proforma_Invoice__r.Orders__r.Name,Productes__c,Machine_Name__c
                 FROM Order_Line_Item__c WHERE Orders__c IN (SELECT Orders__c 
                  FROM Proforma_Invoice__c WHERE Id = :id)];
        
        for (INTEGER S = 0; S < ORDL.size(); S++) {
            ORDL[S].Serial_No__c = S + 1;
        }
    }
    
        public Proforma_Invoice__c getCurrentInvoiceReport() {
        if (currentPageIndex >= 0 && currentPageIndex < InvoiceList.size()) {
            return InvoiceList[currentPageIndex];
        }
        return null;
    }
      public PageReference next() {
        if (currentPageIndex < totalPages - 1) {
            currentPageIndex++;
        }
        return null; // Return a PageReference to stay on the same page
    }
        public PageReference previous() {
        if (currentPageIndex > 0) {
            currentPageIndex--;
        }
        return null; // Return a PageReference to stay on the same page
    }

    public PageReference save() {
        Proforma_Invoice__c currentInvoice = getCurrentInvoiceReport();
        if (currentInvoice != null && id != null) {
            Blob pdfBlob = generatePdfContent(currentInvoice.Id);

            if (pdfBlob != null) {
                String pdfFileName = 'GeneratedPDF.pdf';
                savePdfAsAttachment(currentInvoice.Id, pdfFileName, pdfBlob);
            }
        }
    PageReference recordDetailPage = new PageReference('/' + currentInvoice.Id);
    recordDetailPage.setRedirect(true);
    return recordDetailPage;
    }

    private Blob generatePdfContent(Id InvoiceId) {
        PageReference pdfPage = Page.InvoicePage;
        pdfPage.getParameters().put('id', InvoiceId);
        return pdfPage.getContentAsPDF();
    }

    private void savePdfAsAttachment(Id InvoiceId, String pdfFileName, Blob pdfBlob) {
        Attachment attachment = new Attachment();
        attachment.ParentId = InvoiceId;
        attachment.Name = pdfFileName;
        attachment.Body = pdfBlob;
        insert attachment;
    }
}
/*public class Invoice {
    public static Id id { get; set; }
    public static List<Proforma_Invoice__c> InvoiceList { get; set; }
    public List<Quote_Line_Item__c> QLI {get;set;}
    public List<Order_Line_Item__c>ORDL{get;set;}
    public static Integer currentPageIndex { get; set; }
    public static Integer totalPages { get; set; }
    
    public Invoice(ApexPages.StandardController controller) {
        id = controller.getId();
        InvoiceList = [SELECT Id,Total_Charges__c,State__c,
                       Customer_Name__c,Village__c,
                       Total_Amount__c,Sub_Total__c,Name,
                       Packing_Charges_Amount__c,
                       Packing_Charges__c,Orders__c,Invoice_Number__c,
                       Insurance_Amount__c,Insurance__c,GST_Amount__c,
                       GST__c,Grand_Amount__c,Forwarding_Charges_Amount__c,
                       Forwarding_Charges__c,District__c,Country__c,
                       Commissioning_Charges__c,City__c,CGST__c,CGST_Amount__c,
                       Building_No_Street__c,Amount_Received__c,SGST__c,SGST_Amount__c,
                       Balance_Amount__c FROM Proforma_Invoice__c WHERE id = :id];
        totalPages = InvoiceList.size();
             currentPageIndex = 0;
        
         QLI = [SELECT Product_Name__c,Category1__c, Quantity__c, Final_Price_Final_Price__c, Unit_Price__c, RowNumber__c
    FROM Quote_Line_Item__c WHERE Quotes__r.Proforma_Invoice__c = :id];
        
        for (INTEGER I = 0; I < QLI.size(); I++) {
            QLI[I].RowNumber__c = I + 1;
        }

        
        ORDL = [SELECT Name,Orders__r.Name, Productes__r.Products__c,Product_Description__c, Quantity__c, Final_Price_After_Discount__c, Unit_Rate__c, Value__c,Serial_No__c,Orders__r.Proforma_Invoice__r.Orders__r.Name,Productes__c,Machine_Name__c
                 FROM Order_Line_Item__c WHERE Orders__c IN (SELECT Orders__c 
                  FROM Proforma_Invoice__c WHERE Id = :id)];
        
        for (INTEGER S = 0; S < ORDL.size(); S++) {
            ORDL[S].Serial_No__c = S + 1;
        }
    }
        public static Proforma_Invoice__c getCurrentInvoiceReport() {
        if (currentPageIndex >= 0 && currentPageIndex < InvoiceList.size()) {
            return InvoiceList[currentPageIndex];
        }
        return null;
    }
      public PageReference next() {
        if (currentPageIndex < totalPages - 1) {
            currentPageIndex++;
        }
        return null; // Return a PageReference to stay on the same page
    }
        public PageReference previous() {
        if (currentPageIndex > 0) {
            currentPageIndex--;
        }
        return null; // Return a PageReference to stay on the same page
    }
    public PageReference save() {
    Proforma_Invoice__c currentInvoice = getCurrentInvoiceReport();
    if (currentInvoice != null && id != null) {
        Blob pdfBlob = generatePdfContent(currentInvoice.Id);

        if (pdfBlob != null) {
            Datetime timestamp = System.now();
            String pdfFileName = 'Invoice_' + timestamp + '.pdf';
            savePdfAsAttachment(currentInvoice.Id, pdfFileName, pdfBlob);
            
            System.debug('Attachment saved successfully.');
        } else {
            System.debug('PDF Blob is null.');
        }
    } else {
        System.debug('Current Invoice or Id is null.');
    }
        
        /*PageReference recordDetailPage = new PageReference('/' + currentInvoice.Id);
    recordDetailPage.setRedirect(true);
    return recordDetailPage;
    }


    // Add a null check for currentInvoice before accessing its Id
    PageReference recordDetailPage = (currentInvoice != null) ? new PageReference('/' + + currentInvoice.Id) : null;

    if (recordDetailPage != null) {
        recordDetailPage.setRedirect(true);
    }

    return recordDetailPage;
}



 //  @TestVisible private static Blob generatePdfContent(Id InvoiceId) {
        private Blob generatePdfContent(Id InvoiceId) {
        PageReference pdfPage = Page.InvoicePage;
        pdfPage.getParameters().put('id', InvoiceId);
        return pdfPage.getContentAsPDF();
    }

    //@TestVisible private static void savePdfAsAttachment(Id InvoiceId, String pdfFileName, Blob pdfBlob) {
       private void savePdfAsAttachment(Id InvoiceId, String pdfFileName, Blob pdfBlob) {
    try {
        Attachment attachment = new Attachment();
        attachment.ParentId = InvoiceId;
        attachment.Name = pdfFileName;
        attachment.Body = pdfBlob;
        insert attachment;
    } catch (Exception e) {
        System.debug('Exception occurred while saving attachment: ' + e.getMessage());
    }
}
}*/