force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O - {00000}</displayFormat>
        <label>Order No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Grand_Amount__c  -  Advance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Basic_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Basic_Order_Value__c</fullName>
    <label>Basic Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Building_No_Street__c.field-meta.xml
<CustomField>
    <fullName>Building_No_Street__c</fullName>
    <label>Building No. &amp; Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>CGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Sub_Total__c * CGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Commissioning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Commissioning Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Engineering_Charges__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Charges__c</fullName>
    <label>Engineering Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/FAX_No__c.field-meta.xml
<CustomField>
    <fullName>FAX_No__c</fullName>
    <label>FAX No.</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/First_Concern_Person__c.field-meta.xml
<CustomField>
    <fullName>First_Concern_Person__c</fullName>
    <label>First Concern Person</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Forwarding_Charge__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charge__c</fullName>
    <formula>Basic_Order_Value__c  *  Forwarding_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forwarding Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Grand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Amount__c</fullName>
    <formula>Sub_Total__c  +  CGST_Amount__c  +  IGST_Amount__c  +  SGST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/GST_No__c.field-meta.xml
<CustomField>
    <fullName>GST_No__c</fullName>
    <label>GST No.</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>IGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Second_Concern_Person__c.field-meta.xml
<CustomField>
    <fullName>Second_Concern_Person__c</fullName>
    <label>Second Concern Person</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>SGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Sub_Total__c  *  SGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>Package_Charges__c  +  Forwarding_Charge__c  +  Commissioning_Charges__c  +  Engineering_Charges__c  +  Transportation_Charges__c  +  Transit_Insurance_Amount__c + Basic_Order_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <label>Supplier Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Transit_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Transit_Insurance__c</fullName>
    <defaultValue>0.001</defaultValue>
    <label>Transit Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Transit_Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transit_Insurance_Amount__c</fullName>
    <formula>Basic_Order_Value__c  *  Transit_Insurance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transit Insurance Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Transportation_Charges__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Charges__c</fullName>
    <label>Transportation Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Proforma Invoice</label>
    <nameField>
        <displayFormat>I - {000000}</displayFormat>
        <label>Proforma Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proforma Invoice</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/fields/Building_No_Street__c.field-meta.xml
<CustomField>
    <fullName>Building_No_Street__c</fullName>
    <label>Building No. &amp; Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>CGST%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Total_Charges__c * CGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <defaultValue>0.01</defaultValue>
    <label>Forwarding Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Grand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Amount__c</fullName>
    <formula>Total_Charges__c  +   GST_Amount__c +  Insurance_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <defaultValue>0.09</defaultValue>
    <label>SGST%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <formula>IF( OR(State__c == &apos;Telangana&apos;,State__c == &apos;telangana&apos;,State__c == &apos;TELANGANA&apos;) , Total_Charges__c * SGST__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <formula>IF( OR( BillingStateProvince__c == &apos;Telangana&apos;, BillingStateProvince__c == &apos;telangana&apos;, BillingStateProvince__c == &apos;TELANGANA&apos;), 0.09, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Commissioning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Commissioning_Charges__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Commissioning Charges For Each Machine</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Forwarding_Charges__c.field-meta.xml
<CustomField>
    <fullName>Forwarding_Charges__c</fullName>
    <label>Forwarding Charges (%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <formula>IF(OR( BillingStateProvince__c== &apos;Telangana&apos;, BillingStateProvince__c== &apos;telangana&apos;, BillingStateProvince__c== &apos;TELANGANA&apos;),0,0.18)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <formula>IF( OR( BillingStateProvince__c  == &apos;Telangana&apos;, BillingStateProvince__c  == &apos;telangana&apos;, BillingStateProvince__c  == &apos;TELANGANA&apos;), 0.09, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <formula>Total_Cost__c * VALUE( TEXT( SGST__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Transit_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Transit_Insurance__c</fullName>
    <defaultValue>0.001</defaultValue>
    <label>Transit Insurance</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <formula>Opportunity_Name__r.AccountID__r.Village__c</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderAttachment.cls
public class OrderAttachment {/*
    public Id id { get; set; }
    public List<Order__c> OrderList {get;set;}
    public List<Order_Line_Item__c>ORDL{get;set;}
    public Integer currentPageIndex {get;set;}
    public Integer totalPages { get; set; }
   
    public OrderAttachment(ApexPages.StandardController controller) {
        id = controller.getId();
        OrderList = [SELECT Id, SL_No__c,Village__c,Transportation_Charges__c,Transit_Insurance_Amount__c,Transit_Insurance__c,Supplier_Name__c,SGST__c,State__c,Sub_Total__c,SGST_Amount__c,Second_Concern_Person__c,Advance__c,Balance__c,Basic_Order_Value__c,Building_No_Street__c,CGST__c,CGST_Amount__c,  City__c,Commissioning_Charges__c, Country__c,Customer_Name__c,Date__c,District__c,  Email__c,   Engineering_Charges__c,FAX_No__c,First_Concern_Person__c,Forwarding_Charge__c,Forwarding_Charges__c,Grand_Amount__c,GST_No__c,  IGST__c,IGST_Amount__c,Old_Price__c,Name,Package_Charges__c,    Packing_Charges__c,Phone__c,Phone_1__c,Product_Code__c,Proforma_Invoice__c, Quanity__c,Quotes__c,Remarks__c FROM Order__c WHERE id = :id];
             
        totalPages = OrderList.size();
        currentPageIndex = 0;
        ORDL = new List<Order_Line_Item__c>();
       
         Set<Id> ORDlIds = new Set<Id>();
        for (Order__c OrderRecord : OrderList) {
            ORDlIds.add(OrderRecord.Id);
        }
 
       
        ORDL = [SELECT Name, Orders__r.Name, Productes__r.Products__c, Product_Description__c, Quantity__c, Final_Price_After_Discount__c, Unit_Rate__c, Value__c, Serial_No__c, Orders__r.Proforma_Invoice__r.Orders__r.Name, Productes__c, Machine_Name__c FROM Order_Line_Item__c WHERE Orders__c IN :ORDlIds];
 
       generateSerialNumbers();
    }
 
    private void generateSerialNumbers() {
        for (Integer i = 0; i < ORDL.size(); i++) {
            ORDL[i].Serial_No__c = currentPageIndex * 10 + i + 1;
        }
    }
    public Order__c getCurrentOrderReport() {
        if (currentPageIndex >= 0 && currentPageIndex < OrderList.size()) {
            return OrderList[currentPageIndex];
        }
        return null;
    }
    public PageReference next() {
    if (currentPageIndex < totalPages-1) {
        currentPageIndex++;
    }
    return null;
    }
    public PageReference previous() {
    if (currentPageIndex > 0) {
        currentPageIndex--;
    }
    return null;
    }
    public PageReference save() {
        Order__c orderrep = getCurrentOrderReport();
        if (orderrep != null && id != null) {
            Blob pdfBlob = generatePdfContent(orderrep.Id);
            if (pdfBlob != null) {
                String pdfFileName = 'GeneratedPDF.pdf';
                savePdfAsAttachment(orderrep.Id, pdfFileName, pdfBlob);
            }
        }
        PageReference recordDetailPage = new PageReference('/' + orderrep.Id);
        recordDetailPage.setRedirect(true);
        return recordDetailPage;
    }
    private Blob generatePdfContent(Id orderID) {
        PageReference pdfPage = Page.OrderAttachmentPage;
        pdfPage.getParameters().put('id', orderID);
        return pdfPage.getContentAsPDF();
    }
 
    private void savePdfAsAttachment(Id orderID, String pdfFileName, Blob pdfBlob) {
        Attachment attachment = new Attachment();
        attachment.ParentId = orderID;
        attachment.Name = pdfFileName;
        attachment.Body = pdfBlob;
        insert attachment;
    }*/
}