force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Mill_End_Date_Time__c</fullName>
    <label>Mill Visit End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mill_Planner__c/fields/Mill_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Mill_Start_Date_Time__c</fullName>
    <label>Mill Visit Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/RecordUpdateController.cls
public with sharing class RecordUpdateController {
    @AuraEnabled
    public static void updateLogInTime(Id millPlannerId, DateTime LogInTime) {
        // Retrieve the Mill_Planner__c record by its Id.
        Mill_Planner__c millPlanner = [SELECT Id, Mill_Start_Date_Time__c FROM Mill_Planner__c WHERE Id = :millPlannerId];

        // Update the Mill_Start_Date_Time__c field with the new date time value.
        millPlanner.Mill_Start_Date_Time__c = LogInTime;

        // Update the record in the database.
        update millPlanner;
    }

    @AuraEnabled
    public static void updateLogOutTime(Id millPlannerId,  DateTime LogOutTime) {
        // Retrieve the Mill_Planner__c record by its Id.
        Mill_Planner__c millPlanner = [SELECT Id,Mill_End_Date_Time__c FROM Mill_Planner__c WHERE Id = :millPlannerId];

        // Update the Mill_Start_Date_Time__c field with the new date time value.
        millPlanner.Mill_End_Date_Time__c = LogOutTime;

        // Update the record in the database.
        update millPlanner;
    }
}