force-app/main/default/objects/Mill_Planner__c/Mill_Planner__c.object-meta.xml
<CustomObject>
    <label>Mill Planner</label>
    <nameField>
        <label>Mill Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mill Planner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mill_Planner__c/fields/Follow_Up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date_Time__c</fullName>
    <label>Follow-Up Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Monthly_Planner__c/Monthly_Planner__c.object-meta.xml
<CustomObject>
    <label>Monthly Planner</label>
    <nameField>
        <label>Monthly Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Planners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/testfollowUpTriggerHandler.cls
public class testfollowUpTriggerHandler {
    public static void createEvent(List<Mill_Planner__c> mp, Map<Id, Datetime> oldMp) {
        
        List<Event> eventsToInsert = new List<Event>();
        
        for (Mill_Planner__c millPlanner : mp) {
            Datetime newfollowUpDate = millPlanner.Follow_Up_Date_Time__c;
            Datetime oldfollowUpDate = oldMp.get(millPlanner.Id);
            
            if (newfollowUpDate != oldfollowUpDate) {
                Event ev = new Event();
                ev.WhatId = millPlanner.Id;
                ev.Subject = 'Meeting';
                ev.StartDateTime = millPlanner.Follow_Up_Date_Time__c;
                ev.EndDateTime = millPlanner.Follow_Up_Date_Time__c.addHours(1);
                ev.Description = millPlanner.Feedback__c;
                eventsToInsert.add(ev);
            }
        }
        
        if (!eventsToInsert.isEmpty()) {
            insert eventsToInsert;
        }
    }
    
    Public static void CreateMillPlannerOnFollowUp(List<Mill_Planner__c> mp){
        
        Mill_Planner__c insertMp = new Mill_Planner__c();
        
        Monthly_Planner__c  monthlyPlanner = [select id, Start_Date__c,End_Date__c from Monthly_Planner__c];
        
        
        
      
    }
}